import subprocess

BRANCHES = [
    "legacy-admin-reporting",
    "legacy-api-db", 
    "legacy-portal",
    "legacy-forms",
    "legacy-uploads-storage",
]

def sh(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        return f"ERROR: {e.output}"

for branch in BRANCHES:
    print(f"\n--- {branch} ---")
    
    title = f"{branch}: legacy code migration"
    body = f"""## Legacy Bundle: {branch}

This PR contains legacy code files for the **{branch}** area.

### What's included
- All legacy files for this subsystem
- Ready for review and migration planning

### Files
See the diff for full list of files in this bundle.

---
🤖 Generated by migration automation
"""
    
    cmd = f'gh pr create -R oneaiguru/europe-ttp -B main -H {branch} -d -t "{title}" -b "{body}"'
    result = sh(cmd)
    
    if "ERROR:" in result or "error:" in result:
        print(f"  ✗ {result[:200]}")
    else:
        print(f"  ✓ {result.strip()}")

print("\n✅ PRs created!")
