export const STEPS = {
  'I am authenticated as a Sahaj TTC graduate': {
    pattern: /^I\ am\ authenticated\ as\ a\ Sahaj\ TTC\ graduate$/,
    python: 'test/python/steps/forms_steps.py:67',
    typescript: 'test/typescript/steps/forms_steps.ts:73',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:8', 'specs/features/forms/post_sahaj_ttc_feedback.feature:8'],
  },
  'I am authenticated as a TTC admin': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ admin$/,
    python: 'test/python/steps/forms_steps.py:215',
    typescript: 'test/typescript/steps/forms_steps.ts:293',
    features: ['specs/features/forms/ttc_portal_settings.feature:8'],
  },
  'I am authenticated as a TTC applicant': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ applicant$/,
    python: 'test/python/steps/forms_steps.py:29',
    typescript: 'test/typescript/steps/forms_steps.ts:17',
    features: ['specs/features/forms/ttc_application_us.feature:8', 'specs/features/forms/ttc_application_non_us.feature:8', 'specs/features/forms/ttc_applicant_profile.feature:8', 'specs/features/forms/dsn_application.feature:8'],
  },
  'I am authenticated as a TTC graduate': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ graduate$/,
    python: 'test/python/steps/forms_steps.py:178',
    typescript: 'test/typescript/steps/forms_steps.ts:238',
    features: ['specs/features/forms/post_ttc_self_eval.feature:8', 'specs/features/forms/post_ttc_feedback.feature:8'],
  },
  'I am authenticated as a non-admin user': {
    pattern: /^I\ am\ authenticated\ as\ a\ non\-admin\ user$/,
    python: 'test/python/steps/admin_steps.py:85',
    typescript: 'test/typescript/steps/admin_steps.ts:69',
    features: ['specs/features/admin/permissions.feature:8'],
  },
  'I am authenticated as an admin user': {
    pattern: /^I\ am\ authenticated\ as\ an\ admin\ user$/,
    python: 'test/python/steps/admin_steps.py:77',
    typescript: 'test/typescript/steps/admin_steps.ts:59',
    features: ['specs/features/admin/access.feature:8', 'specs/features/admin/reports_pages.feature:8', 'specs/features/admin/settings.feature:8', 'specs/features/user/reporting_get_form_data.feature:8', 'specs/features/reports/user_summary.feature:8', 'specs/features/reports/user_summary.feature:14', 'specs/features/reports/user_integrity.feature:8', 'specs/features/reports/user_integrity.feature:14', 'specs/features/reports/user_integrity.feature:20', 'specs/features/reports/user_report.feature:8', 'specs/features/reports/user_report.feature:14', 'specs/features/reports/user_report.feature:20', 'specs/features/reports/print_form.feature:8', 'specs/features/reports/participant_list.feature:8'],
  },
  'I am authenticated as an evaluator': {
    pattern: /^I\ am\ authenticated\ as\ an\ evaluator$/,
    python: 'test/python/steps/forms_steps.py:123',
    typescript: 'test/typescript/steps/forms_steps.ts:157',
    features: ['specs/features/forms/ttc_evaluation.feature:8', 'specs/features/forms/ttc_evaluator_profile.feature:8'],
  },
  'I am authenticated on the TTC portal': {
    pattern: /^I\ am\ authenticated\ on\ the\ TTC\ portal$/,
    python: 'test/python/steps/auth_steps.py:69',
    typescript: 'test/typescript/steps/auth_steps.ts:41',
    features: ['specs/features/auth/logout.feature:8', 'specs/features/portal/home.feature:8', 'specs/features/portal/tabs.feature:8', 'specs/features/uploads/photo_upload.feature:8', 'specs/features/uploads/document_upload.feature:8', 'specs/features/api/upload_form.feature:8', 'specs/features/user/form_data_upload.feature:8', 'specs/features/user/config_management.feature:8', 'specs/features/user/config_management.feature:14', 'specs/features/reports/certificate.feature:8'],
  },
  'I am on the TTC portal login page': {
    pattern: /^I\ am\ on\ the\ TTC\ portal\ login\ page$/,
    python: 'test/python/steps/auth_steps.py:55',
    typescript: 'test/typescript/steps/auth_steps.ts:35',
    features: ['specs/features/auth/login.feature:8', 'specs/features/auth/password_reset.feature:8'],
  },
  'I have multiple form instances for a form type': {
    pattern: /^I\ have\ multiple\ form\ instances\ for\ a\ form\ type$/,
    python: 'test/python/steps/user_steps.py:433',
    typescript: 'test/typescript/steps/user_steps.ts:393',
    features: ['specs/features/user/get_form_instances.feature:8'],
  },
  'I have previously saved form data for a form instance': {
    pattern: /^I\ have\ previously\ saved\ form\ data\ for\ a\ form\ instance$/,
    python: 'test/python/steps/user_steps.py:323',
    typescript: 'test/typescript/steps/user_steps.ts:313',
    features: ['specs/features/user/get_form_data.feature:8'],
  },
  'I open a printable form page': {
    pattern: /^I\ open\ a\ printable\ form\ page$/,
    python: 'test/python/steps/reports_steps.py:372',
    typescript: 'test/typescript/steps/reports_steps.ts:201',
    features: ['specs/features/reports/print_form.feature:9'],
  },
  'I open an admin-only page': {
    pattern: /^I\ open\ an\ admin\-only\ page$/,
    python: 'test/python/steps/admin_steps.py:102',
    typescript: 'test/typescript/steps/admin_steps.ts:85',
    features: ['specs/features/admin/permissions.feature:9'],
  },
  'I open the DSN application form': {
    pattern: /^I\ open\ the\ DSN\ application\ form$/,
    python: 'test/python/steps/forms_steps.py:35',
    typescript: 'test/typescript/steps/forms_steps.ts:23',
    features: ['specs/features/forms/dsn_application.feature:9'],
  },
  'I open the TTC applicant profile form': {
    pattern: /^I\ open\ the\ TTC\ applicant\ profile\ form$/,
    python: 'test/python/steps/forms_steps.py:145',
    typescript: 'test/typescript/steps/forms_steps.ts:188',
    features: ['specs/features/forms/ttc_applicant_profile.feature:9'],
  },
  'I open the TTC application form for a non-US country': {
    pattern: /^I\ open\ the\ TTC\ application\ form\ for\ a\ non\-US\ country$/,
    python: 'test/python/steps/forms_steps.py:67',
    typescript: 'test/typescript/steps/forms_steps.ts:73',
    features: ['specs/features/forms/ttc_application_non_us.feature:9'],
  },
  'I open the TTC application form for the United States': {
    pattern: /^I\ open\ the\ TTC\ application\ form\ for\ the\ United\ States$/,
    python: 'test/python/steps/forms_steps.py:51',
    typescript: 'test/typescript/steps/forms_steps.ts:48',
    features: ['specs/features/forms/ttc_application_us.feature:9'],
  },
  'I open the TTC evaluation form': {
    pattern: /^I\ open\ the\ TTC\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:129',
    typescript: 'test/typescript/steps/forms_steps.ts:163',
    features: ['specs/features/forms/ttc_evaluation.feature:9'],
  },
  'I open the TTC evaluator profile form': {
    pattern: /^I\ open\ the\ TTC\ evaluator\ profile\ form$/,
    python: 'test/python/steps/forms_steps.py:161',
    typescript: 'test/typescript/steps/forms_steps.ts:211',
    features: ['specs/features/forms/ttc_evaluator_profile.feature:9'],
  },
  'I open the TTC portal home': {
    pattern: /^I\ open\ the\ TTC\ portal\ home$/,
    python: 'test/python/steps/portal_steps.py:93',
    typescript: 'test/typescript/steps/portal_steps.ts:88',
    features: ['specs/features/portal/home.feature:9'],
  },
  'I open the TTC portal settings form': {
    pattern: /^I\ open\ the\ TTC\ portal\ settings\ form$/,
    python: 'test/python/steps/forms_steps.py:220',
    typescript: 'test/typescript/steps/forms_steps.ts:298',
    features: ['specs/features/forms/ttc_portal_settings.feature:9'],
  },
  'I open the admin dashboard page': {
    pattern: /^I\ open\ the\ admin\ dashboard\ page$/,
    python: 'test/python/steps/admin_steps.py:97',
    typescript: 'test/typescript/steps/admin_steps.ts:79',
    features: ['specs/features/admin/access.feature:9'],
  },
  'I open the admin reports list page': {
    pattern: /^I\ open\ the\ admin\ reports\ list\ page$/,
    python: 'test/python/steps/admin_steps.py:112',
    typescript: 'test/typescript/steps/admin_steps.ts:107',
    features: ['specs/features/admin/reports_pages.feature:9'],
  },
  'I open the admin settings page': {
    pattern: /^I\ open\ the\ admin\ settings\ page$/,
    python: 'test/python/steps/admin_steps.py:123',
    typescript: 'test/typescript/steps/admin_steps.ts:127',
    features: ['specs/features/admin/settings.feature:9'],
  },
  'I open the post-Sahaj TTC feedback form': {
    pattern: /^I\ open\ the\ post\-Sahaj\ TTC\ feedback\ form$/,
    python: 'test/python/steps/forms_steps.py:73',
    typescript: 'test/typescript/steps/forms_steps.ts:79',
    features: ['specs/features/forms/post_sahaj_ttc_feedback.feature:9'],
  },
  'I open the post-Sahaj TTC self evaluation form': {
    pattern: /^I\ open\ the\ post\-Sahaj\ TTC\ self\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:89',
    typescript: 'test/typescript/steps/forms_steps.ts:104',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:9'],
  },
  'I open the post-TTC feedback form': {
    pattern: /^I\ open\ the\ post\-TTC\ feedback\ form$/,
    python: 'test/python/steps/forms_steps.py:198',
    typescript: 'test/typescript/steps/forms_steps.ts:266',
    features: ['specs/features/forms/post_ttc_feedback.feature:9'],
  },
  'I open the post-TTC self evaluation form': {
    pattern: /^I\ open\ the\ post\-TTC\ self\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:184',
    typescript: 'test/typescript/steps/forms_steps.ts:244',
    features: ['specs/features/forms/post_ttc_self_eval.feature:9'],
  },
  'I request a certificate PDF': {
    pattern: /^I\ request\ a\ certificate\ PDF$/,
    python: 'test/python/steps/reports_steps.py:488',
    typescript: 'test/typescript/steps/reports_steps.ts:292',
    features: ['specs/features/reports/certificate.feature:9'],
  },
  'I request a password reset for my Google account': {
    pattern: /^I\ request\ a\ password\ reset\ for\ my\ Google\ account$/,
    python: 'test/python/steps/auth_steps.py:118',
    typescript: 'test/typescript/steps/auth_steps.ts:68',
    features: ['specs/features/auth/password_reset.feature:9'],
  },
  'I request a signed upload URL for a document': {
    pattern: /^I\ request\ a\ signed\ upload\ URL\ for\ a\ document$/,
    python: 'test/python/steps/uploads_steps.py:28',
    typescript: 'test/typescript/steps/uploads_steps.ts:31',
    features: ['specs/features/uploads/document_upload.feature:9'],
  },
  'I request a signed upload URL for a profile photo': {
    pattern: /^I\ request\ a\ signed\ upload\ URL\ for\ a\ profile\ photo$/,
    python: 'test/python/steps/uploads_steps.py:6',
    typescript: 'test/typescript/steps/uploads_steps.ts:4',
    features: ['specs/features/uploads/photo_upload.feature:9'],
  },
  'I request a signed upload URL without authentication': {
    pattern: /^I\ request\ a\ signed\ upload\ URL\ without\ authentication$/,
    python: 'test/python/steps/uploads_steps.py:53',
    typescript: 'test/typescript/steps/uploads_steps.ts:65',
    features: ['specs/features/uploads/upload_security.feature:11'],
  },
  'I request a signed URL with filepath {string}': {
    pattern: /^I\ request\ a\ signed\ URL\ with\ filepath\ "([^"]*)"$/,
    python: 'test/python/steps/uploads_steps.py:84',
    typescript: 'test/typescript/steps/uploads_steps.ts:100',
    features: ['specs/features/uploads/upload_security.feature:13', 'specs/features/uploads/upload_security.feature:25'],
  },
  'I request a signed URL with content type {string}': {
    pattern: /^I\ request\ a\ signed\ URL\ with\ content\ type\ "([^"]*)"$/,
    python: 'test/python/steps/uploads_steps.py:115',
    typescript: 'test/typescript/steps/uploads_steps.ts:129',
    features: ['specs/features/uploads/upload_security.feature:19', 'specs/features/uploads/upload_security.feature:25'],
  },
  'I should receive a 401 error': {
    pattern: /^I\ should\ receive\ a\ 401\ error$/,
    python: 'test/python/steps/uploads_steps.py:64',
    typescript: 'test/typescript/steps/uploads_steps.ts:76',
    features: ['specs/features/uploads/upload_security.feature:12'],
  },
  'I should receive a 400 error': {
    pattern: /^I\ should\ receive\ a\ 400\ error$/,
    python: 'test/python/steps/uploads_steps.py:72',
    typescript: 'test/typescript/steps/uploads_steps.ts:84',
    features: ['specs/features/uploads/upload_security.feature:14', 'specs/features/uploads/upload_security.feature:20'],
  },
  'no signed URL should be generated': {
    pattern: /^no\ signed\ URL\ should\ be\ generated$/,
    python: 'test/python/steps/uploads_steps.py:78',
    typescript: 'test/typescript/steps/uploads_steps.ts:94',
    features: ['specs/features/uploads/upload_security.feature:13'],
  },
  'the error should mention {string}': {
    pattern: /^the\ error\ should\ mention\ "([^"]*)"$/,
    python: 'test/python/steps/uploads_steps.py:107',
    typescript: 'test/typescript/steps/uploads_steps.ts:120',
    features: ['specs/features/uploads/upload_security.feature:15', 'specs/features/uploads/upload_security.feature:21'],
  },
  'the signed URL should expire within {int} minutes': {
    pattern: /^the\ signed\ URL\ should\ expire\ within\ (\d+)\ minutes$/,
    python: 'test/python/steps/uploads_steps.py:145',
    typescript: 'test/typescript/steps/uploads_steps.ts:156',
    features: ['specs/features/uploads/upload_security.feature:27'],
  },
  'I request a tab template page': {
    pattern: /^I\ request\ a\ tab\ template\ page$/,
    python: 'test/python/steps/portal_steps.py:261',
    typescript: 'test/typescript/steps/portal_steps.ts:185',
    features: ['specs/features/portal/tabs.feature:9'],
  },
  'I request form data for a specific user via reporting': {
    pattern: /^I\ request\ form\ data\ for\ a\ specific\ user\ via\ reporting$/,
    python: 'test/python/steps/user_steps.py:507',
    typescript: 'test/typescript/steps/user_steps.ts:472',
    features: ['specs/features/user/reporting_get_form_data.feature:9'],
  },
  'I should receive that user\'s form data': {
    pattern: /^I\ should\ receive\ that\ user\'s\ form\ data$/,
    python: 'test/python/steps/user_steps.py:532',
    typescript: 'test/typescript/steps/user_steps.ts:498',
    features: ['specs/features/user/reporting_get_form_data.feature:10'],
  },
  'I request my user configuration': {
    pattern: /^I\ request\ my\ user\ configuration$/,
    python: 'test/python/steps/user_steps.py:232',
    typescript: 'test/typescript/steps/user_steps.ts:212',
    features: ['specs/features/user/config_management.feature:9'],
  },
  'I request that form data': {
    pattern: /^I\ request\ that\ form\ data$/,
    python: 'test/python/steps/user_steps.py:377',
    typescript: 'test/typescript/steps/user_steps.ts:335',
    features: ['specs/features/user/get_form_data.feature:9'],
  },
  'I request the combined user application report': {
    pattern: /^I\ request\ the\ combined\ user\ application\ report$/,
    python: 'test/python/steps/reports_steps.py:278',
    typescript: 'test/typescript/steps/reports_steps.ts:157',
    features: ['specs/features/reports/user_report.feature:15'],
  },
  'I request the list of form instances': {
    pattern: /^I\ request\ the\ list\ of\ form\ instances$/,
    python: 'test/python/steps/user_steps.py:465',
    typescript: 'test/typescript/steps/user_steps.ts:418',
    features: ['specs/features/user/get_form_instances.feature:9'],
  },
  'I request the participant list report': {
    pattern: /^I\ request\ the\ participant\ list\ report$/,
    python: 'test/python/steps/reports_steps.py:444',
    typescript: 'test/typescript/steps/reports_steps.ts:247',
    features: ['specs/features/reports/participant_list.feature:9'],
  },
  'I request the user application report as HTML': {
    pattern: /^I\ request\ the\ user\ application\ report\ as\ HTML$/,
    python: 'test/python/steps/reports_steps.py:238',
    typescript: 'test/typescript/steps/reports_steps.ts:134',
    features: ['specs/features/reports/user_report.feature:9'],
  },
  'I request the user application report as forms': {
    pattern: /^I\ request\ the\ user\ application\ report\ as\ forms$/,
    python: 'test/python/steps/reports_steps.py:318',
    typescript: 'test/typescript/steps/reports_steps.ts:177',
    features: ['specs/features/reports/user_report.feature:21'],
  },
  'I request the user integrity report by user': {
    pattern: /^I\ request\ the\ user\ integrity\ report\ by\ user$/,
    python: 'test/python/steps/reports_steps.py:161',
    typescript: 'test/typescript/steps/reports_steps.ts:82',
    features: ['specs/features/reports/user_integrity.feature:15'],
  },
  'I request the user summary report by user': {
    pattern: /^I\ request\ the\ user\ summary\ report\ by\ user$/,
    python: 'test/python/steps/reports_steps.py:80',
    typescript: 'test/typescript/steps/reports_steps.ts:34',
    features: ['specs/features/reports/user_summary.feature:15'],
  },
  'I run the user integrity postload job': {
    pattern: /^I\ run\ the\ user\ integrity\ postload\ job$/,
    python: 'test/python/steps/reports_steps.py:200',
    typescript: 'test/typescript/steps/reports_steps.ts:105',
    features: ['specs/features/reports/user_integrity.feature:21'],
  },
  'I run the user integrity report load job': {
    pattern: /^I\ run\ the\ user\ integrity\ report\ load\ job$/,
    python: 'test/python/steps/reports_steps.py:119',
    typescript: 'test/typescript/steps/reports_steps.ts:64',
    features: ['specs/features/reports/user_integrity.feature:9'],
  },
  'I run the user summary report load job': {
    pattern: /^I\ run\ the\ user\ summary\ report\ load\ job$/,
    python: 'test/python/steps/reports_steps.py:40',
    typescript: 'test/typescript/steps/reports_steps.ts:16',
    features: ['specs/features/reports/user_summary.feature:9'],
  },
  'I should be redirected to the TTC portal home': {
    pattern: /^I\ should\ be\ redirected\ to\ the\ TTC\ portal\ home$/,
    python: 'test/python/steps/auth_steps.py:86',
    typescript: 'test/typescript/steps/auth_steps.ts:51',
    features: ['specs/features/auth/login.feature:10'],
  },
  'I should be redirected to the TTC portal login page': {
    pattern: /^I\ should\ be\ redirected\ to\ the\ TTC\ portal\ login\ page$/,
    python: 'test/python/steps/auth_steps.py:135',
    typescript: 'test/typescript/steps/auth_steps.ts:77',
    features: ['specs/features/auth/logout.feature:10'],
  },
  'I should receive a password reset prompt from the identity provider': {
    pattern: /^I\ should\ receive\ a\ password\ reset\ prompt\ from\ the\ identity\ provider$/,
    python: 'test/python/steps/auth_steps.py:147',
    typescript: 'test/typescript/steps/auth_steps.ts:96',
    features: ['specs/features/auth/password_reset.feature:10'],
  },
  'I should receive a signed URL and upload key for the document': {
    pattern: /^I\ should\ receive\ a\ signed\ URL\ and\ upload\ key\ for\ the\ document$/,
    python: 'test/python/steps/uploads_steps.py:41',
    typescript: 'test/typescript/steps/uploads_steps.ts:41',
    features: ['specs/features/uploads/document_upload.feature:10'],
  },
  'I should receive a signed URL and upload key for the photo': {
    pattern: /^I\ should\ receive\ a\ signed\ URL\ and\ upload\ key\ for\ the\ photo$/,
    python: 'test/python/steps/uploads_steps.py:19',
    typescript: 'test/typescript/steps/uploads_steps.ts:14',
    features: ['specs/features/uploads/photo_upload.feature:10'],
  },
  'I should receive my saved configuration': {
    pattern: /^I\ should\ receive\ my\ saved\ configuration$/,
    python: 'test/python/steps/user_steps.py:241',
    typescript: 'test/typescript/steps/user_steps.ts:222',
    features: ['specs/features/user/config_management.feature:10'],
  },
  'I should receive the available form instances': {
    pattern: /^I\ should\ receive\ the\ available\ form\ instances$/,
    python: 'test/python/steps/user_steps.py:471',
    typescript: 'test/typescript/steps/user_steps.ts:427',
    features: ['specs/features/user/get_form_instances.feature:10'],
  },
  'I should receive the combined user application data': {
    pattern: /^I\ should\ receive\ the\ combined\ user\ application\ data$/,
    python: 'test/python/steps/reports_steps.py:298',
    typescript: 'test/typescript/steps/reports_steps.ts:166',
    features: ['specs/features/reports/user_report.feature:16'],
  },
  'I should receive the participant list output': {
    pattern: /^I\ should\ receive\ the\ participant\ list\ output$/,
    python: 'test/python/steps/reports_steps.py:464',
    typescript: 'test/typescript/steps/reports_steps.ts:266',
    features: ['specs/features/reports/participant_list.feature:10'],
  },
  'I should receive the stored form data': {
    pattern: /^I\ should\ receive\ the\ stored\ form\ data$/,
    python: 'test/python/steps/user_steps.py:391',
    typescript: 'test/typescript/steps/user_steps.ts:350',
    features: ['specs/features/user/get_form_data.feature:10'],
  },
  'I should receive the user application HTML': {
    pattern: /^I\ should\ receive\ the\ user\ application\ HTML$/,
    python: 'test/python/steps/reports_steps.py:258',
    typescript: 'test/typescript/steps/reports_steps.ts:143',
    features: ['specs/features/reports/user_report.feature:10'],
  },
  'I should receive the user application form data': {
    pattern: /^I\ should\ receive\ the\ user\ application\ form\ data$/,
    python: 'test/python/steps/reports_steps.py:338',
    typescript: 'test/typescript/steps/reports_steps.ts:186',
    features: ['specs/features/reports/user_report.feature:22'],
  },
  'I should receive the user integrity data': {
    pattern: /^I\ should\ receive\ the\ user\ integrity\ data$/,
    python: 'test/python/steps/reports_steps.py:181',
    typescript: 'test/typescript/steps/reports_steps.ts:91',
    features: ['specs/features/reports/user_integrity.feature:16'],
  },
  'I should receive the user summary data': {
    pattern: /^I\ should\ receive\ the\ user\ summary\ data$/,
    python: 'test/python/steps/reports_steps.py:100',
    typescript: 'test/typescript/steps/reports_steps.ts:43',
    features: ['specs/features/reports/user_summary.feature:16'],
  },
  'I should see a printable form view': {
    pattern: /^I\ should\ see\ a\ printable\ form\ view$/,
    python: 'test/python/steps/reports_steps.py:421',
    typescript: 'test/typescript/steps/reports_steps.ts:225',
    features: ['specs/features/reports/print_form.feature:10'],
  },
  'I should see an unauthorized message': {
    pattern: /^I\ should\ see\ an\ unauthorized\ message$/,
    python: 'test/python/steps/admin_steps.py:121',
    typescript: 'test/typescript/steps/admin_steps.ts:102',
    features: ['specs/features/admin/permissions.feature:10'],
  },
  'I should see my profile details and available reports': {
    pattern: /^I\ should\ see\ my\ profile\ details\ and\ available\ reports$/,
    python: 'test/python/steps/portal_steps.py:138',
    typescript: 'test/typescript/steps/portal_steps.ts:115',
    features: ['specs/features/portal/home.feature:10'],
  },
  'I should see the DSN application questions': {
    pattern: /^I\ should\ see\ the\ DSN\ application\ questions$/,
    python: 'test/python/steps/forms_steps.py:44',
    typescript: 'test/typescript/steps/forms_steps.ts:38',
    features: ['specs/features/forms/dsn_application.feature:10'],
  },
  'I should see the TTC applicant profile questions': {
    pattern: /^I\ should\ see\ the\ TTC\ applicant\ profile\ questions$/,
    python: 'test/python/steps/forms_steps.py:154',
    typescript: 'test/typescript/steps/forms_steps.ts:203',
    features: ['specs/features/forms/ttc_applicant_profile.feature:10'],
  },
  'I should see the TTC application questions for that country': {
    pattern: /^I\ should\ see\ the\ TTC\ application\ questions\ for\ that\ country$/,
    python: 'test/python/steps/forms_steps.py:78',
    typescript: 'test/typescript/steps/forms_steps.ts:91',
    features: ['specs/features/forms/ttc_application_non_us.feature:10'],
  },
  'I should see the TTC application questions for the United States': {
    pattern: /^I\ should\ see\ the\ TTC\ application\ questions\ for\ the\ United\ States$/,
    python: 'test/python/steps/forms_steps.py:60',
    typescript: 'test/typescript/steps/forms_steps.ts:63',
    features: ['specs/features/forms/ttc_application_us.feature:10'],
  },
  'I should see the TTC evaluation questions': {
    pattern: /^I\ should\ see\ the\ TTC\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:138',
    typescript: 'test/typescript/steps/forms_steps.ts:178',
    features: ['specs/features/forms/ttc_evaluation.feature:10'],
  },
  'I should see the TTC evaluator profile questions': {
    pattern: /^I\ should\ see\ the\ TTC\ evaluator\ profile\ questions$/,
    python: 'test/python/steps/forms_steps.py:170',
    typescript: 'test/typescript/steps/forms_steps.ts:227',
    features: ['specs/features/forms/ttc_evaluator_profile.feature:10'],
  },
  'I should see the TTC portal settings questions': {
    pattern: /^I\ should\ see\ the\ TTC\ portal\ settings\ questions$/,
    python: 'test/python/steps/forms_steps.py:229',
    typescript: 'test/typescript/steps/forms_steps.ts:307',
    features: ['specs/features/forms/ttc_portal_settings.feature:10'],
  },
  'I should see the admin dashboard content': {
    pattern: /^I\ should\ see\ the\ admin\ dashboard\ content$/,
    python: 'test/python/steps/admin_steps.py:114',
    typescript: 'test/typescript/steps/admin_steps.ts:95',
    features: ['specs/features/admin/access.feature:10'],
  },
  'I should see the admin settings content': {
    pattern: /^I\ should\ see\ the\ admin\ settings\ content$/,
    python: 'test/python/steps/admin_steps.py:148',
    typescript: 'test/typescript/steps/admin_steps.ts:150',
    features: ['specs/features/admin/settings.feature:10'],
  },
  'I should see the disabled notice': {
    pattern: /^I\ should\ see\ the\ disabled\ notice$/,
    python: 'test/python/steps/portal_steps.py:223',
    typescript: 'test/typescript/steps/portal_steps.ts:157',
    features: ['specs/features/portal/disabled.feature:10'],
  },
  'I should see the list of available report pages': {
    pattern: /^I\ should\ see\ the\ list\ of\ available\ report\ pages$/,
    python: 'test/python/steps/admin_steps.py:137',
    typescript: 'test/typescript/steps/admin_steps.ts:130',
    features: ['specs/features/admin/reports_pages.feature:10'],
  },
  'I should see the post-Sahaj TTC feedback questions': {
    pattern: /^I\ should\ see\ the\ post\-Sahaj\ TTC\ feedback\ questions$/,
    python: 'test/python/steps/forms_steps.py:82',
    typescript: 'test/typescript/steps/forms_steps.ts:94',
    features: ['specs/features/forms/post_sahaj_ttc_feedback.feature:10'],
  },
  'I should see the post-Sahaj TTC self evaluation questions': {
    pattern: /^I\ should\ see\ the\ post\-Sahaj\ TTC\ self\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:98',
    typescript: 'test/typescript/steps/forms_steps.ts:119',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:10'],
  },
  'I should see the post-TTC feedback questions': {
    pattern: /^I\ should\ see\ the\ post\-TTC\ feedback\ questions$/,
    python: 'test/python/steps/forms_steps.py:204',
    typescript: 'test/typescript/steps/forms_steps.ts:280',
    features: ['specs/features/forms/post_ttc_feedback.feature:10'],
  },
  'I should see the post-TTC self evaluation questions': {
    pattern: /^I\ should\ see\ the\ post\-TTC\ self\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:193',
    typescript: 'test/typescript/steps/forms_steps.ts:259',
    features: ['specs/features/forms/post_ttc_self_eval.feature:10'],
  },
  'I should see the rendered tab content with user context': {
    pattern: /^I\ should\ see\ the\ rendered\ tab\ content\ with\ user\ context$/,
    python: 'test/python/steps/portal_steps.py:290',
    typescript: 'test/typescript/steps/portal_steps.ts:208',
    features: ['specs/features/portal/tabs.feature:10'],
  },
  'I sign in with a valid Google account': {
    pattern: /^I\ sign\ in\ with\ a\ valid\ Google\ account$/,
    python: 'test/python/steps/auth_steps.py:69',
    typescript: 'test/typescript/steps/auth_steps.ts:41',
    features: ['specs/features/auth/login.feature:9'],
  },
  'I sign out of the TTC portal': {
    pattern: /^I\ sign\ out\ of\ the\ TTC\ portal$/,
    python: 'test/python/steps/auth_steps.py:105',
    typescript: 'test/typescript/steps/auth_steps.ts:61',
    features: ['specs/features/auth/logout.feature:9'],
  },
  'I submit form data to the upload form API': {
    pattern: /^I\ submit\ form\ data\ to\ the\ upload\ form\ API$/,
    python: 'test/python/steps/api_steps.py:121',
    typescript: 'test/typescript/steps/api_steps.ts:69',
    features: ['specs/features/api/upload_form.feature:9'],
  },
  'I update my user configuration': {
    pattern: /^I\ update\ my\ user\ configuration$/,
    python: 'test/python/steps/user_steps.py:250',
    typescript: 'test/typescript/steps/user_steps.ts:230',
    features: ['specs/features/user/config_management.feature:15'],
  },
  'I upload form data for a specific form instance': {
    pattern: /^I\ upload\ form\ data\ for\ a\ specific\ form\ instance$/,
    python: 'test/python/steps/user_steps.py:120',
    typescript: 'test/typescript/steps/user_steps.ts:147',
    features: ['specs/features/user/form_data_upload.feature:9'],
  },
  'I visit the disabled page': {
    pattern: /^I\ visit\ the\ disabled\ page$/,
    python: 'test/python/steps/portal_steps.py:201',
    typescript: 'test/typescript/steps/portal_steps.ts:152',
    features: ['specs/features/portal/disabled.feature:9'],
  },
  'a certificate PDF should be generated': {
    pattern: /^a\ certificate\ PDF\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:506',
    typescript: 'test/typescript/steps/reports_steps.ts:302',
    features: ['specs/features/reports/certificate.feature:10'],
  },
  'a user integrity file should be generated': {
    pattern: /^a\ user\ integrity\ file\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:138',
    typescript: 'test/typescript/steps/reports_steps.ts:72',
    features: ['specs/features/reports/user_integrity.feature:10'],
  },
  'a user summary file should be generated': {
    pattern: /^a\ user\ summary\ file\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:59',
    typescript: 'test/typescript/steps/reports_steps.ts:24',
    features: ['specs/features/reports/user_summary.feature:10'],
  },
  'an applicant enrolled list should be generated': {
    pattern: /^an\ applicant\ enrolled\ list\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:219',
    typescript: 'test/typescript/steps/reports_steps.ts:114',
    features: ['specs/features/reports/user_integrity.feature:22'],
  },
  'my configuration should be saved': {
    pattern: /^my\ configuration\ should\ be\ saved$/,
    python: 'test/python/steps/user_steps.py:261',
    typescript: 'test/typescript/steps/user_steps.ts:242',
    features: ['specs/features/user/config_management.feature:16'],
  },
  'my form data should be stored for that instance': {
    pattern: /^my\ form\ data\ should\ be\ stored\ for\ that\ instance$/,
    python: 'test/python/steps/user_steps.py:191',
    typescript: 'test/typescript/steps/user_steps.ts:174',
    features: ['specs/features/user/form_data_upload.feature:10'],
  },
  'the API should accept the form submission': {
    pattern: /^the\ API\ should\ accept\ the\ form\ submission$/,
    python: 'test/python/steps/api_steps.py:166',
    typescript: 'test/typescript/steps/api_steps.ts:95',
    features: ['specs/features/api/upload_form.feature:10'],
  },
  'I submit a valid form data payload of {int} bytes': {
    pattern: /^I\ submit\ a\ valid\ form\ data\ payload\ of\ (\d+)\ bytes$/,
    python: 'test/python/steps/api_steps.py:173',
    typescript: 'test/typescript/steps/api_steps.ts:174',
    features: ['specs/features/api/upload_form_body_size.feature:10'],
  },
  'I submit a form data payload of {int} bytes': {
    pattern: /^I\ submit\ a\ form\ data\ payload\ of\ (\d+)\ bytes$/,
    python: 'test/python/steps/api_steps.py:180',
    typescript: 'test/typescript/steps/api_steps.ts:174',
    features: ['specs/features/api/upload_form_body_size.feature:15', 'specs/features/api/upload_form_body_size.feature:30'],
  },
  'I submit a form data payload of {int} bytes without content-length header': {
    pattern: /^I\ submit\ a\ form\ data\ payload\ of\ (\d+)\ bytes\ without\ content-length\ header$/,
    python: 'test/python/steps/api_steps.py:187',
    typescript: 'test/typescript/steps/api_steps.ts:197',
    features: ['specs/features/api/upload_form_body_size.feature:22', 'specs/features/api/upload_form_body_size.feature:35'],
  },
  'the API should return status {int}': {
    pattern: /^the\ API\ should\ return\ status\ (\d+)$/,
    python: 'test/python/steps/api_steps.py:194',
    typescript: 'test/typescript/steps/api_steps.ts:220',
    features: ['specs/features/api/upload_form_body_size.feature:11', 'specs/features/api/upload_form_body_size.feature:16', 'specs/features/api/upload_form_body_size.feature:23', 'specs/features/api/upload_form_body_size.feature:36'],
  },
  'the API response should have {string} equal to {string}': {
    pattern: /^the\ API\ response\ should\ have\ ([^\s]+)\ equal\ to\ "([^"]+)"$/,
    python: 'test/python/steps/api_steps.py:204',
    typescript: 'test/typescript/steps/api_steps.ts:224',
    features: ['specs/features/api/upload_form_body_size.feature:12', 'specs/features/api/upload_form_body_size.feature:17', 'specs/features/api/upload_form_body_size.feature:24', 'specs/features/api/upload_form_body_size.feature:37'],
  },
  'the TTC portal is in disabled mode': {
    pattern: /^the\ TTC\ portal\ is\ in\ disabled\ mode$/,
    python: 'test/python/steps/portal_steps.py:193',
    typescript: 'test/typescript/steps/portal_steps.ts:147',
    features: ['specs/features/portal/disabled.feature:8'],
  },
  // E2E API Steps - keys match literal step text from features
  'I am authenticated as admin': {
    pattern: /^I\ am\ authenticated\ as\ admin$/,
    python: 'test/python/steps/e2e_api_steps.py:33',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:157',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:41', 'specs/features/e2e/deadline_and_whitelist_override.feature:22', 'specs/features/e2e/deadline_and_whitelist_override.feature:47'],
  },
  'I have completed my applicant profile': {
    pattern: /^I\ have\ completed\ my\ applicant\ profile$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:10'],
  },
  'I have uploaded my photo': {
    pattern: /^I\ have\ uploaded\ my\ photo$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:11'],
  },
  'I run the user summary job': {
    pattern: /^I\ run\ the\ user\ summary\ job$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:43'],
  },
  'I run the integrity report': {
    pattern: /^I\ run\ the\ integrity\ report$/,
    python: 'test/python/steps/e2e_api_steps.py:334',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:416',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:40'],
  },
  'I run the user integrity report': {
    pattern: /^I\ run\ the\ user\ integrity\ report$/,
    python: 'test/python/steps/integrity_steps.py:110',
    typescript: 'test/typescript/steps/integrity_steps.ts:176',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:9', 'specs/features/e2e/reporting_integrity_checks.feature:15', 'specs/features/e2e/reporting_integrity_checks.feature:22', 'specs/features/e2e/reporting_integrity_checks.feature:27'],
  },
  'applicant has submitted TTC application': {
    pattern: /^applicant\ has\ submitted\ TTC\ application$/,
    python: 'test/python/steps/certificate_steps.py:93',
    typescript: 'test/typescript/steps/certificate_steps.ts:171',
    features: ['specs/features/e2e/certificate_eligibility.feature:9', 'specs/features/e2e/certificate_eligibility.feature:30', 'specs/features/e2e/certificate_eligibility.feature:48', 'specs/features/e2e/certificate_eligibility.feature:69', 'specs/features/e2e/certificate_eligibility.feature:89', 'specs/features/e2e/certificate_eligibility.feature:110', 'specs/features/e2e/certificate_gating.feature:20', 'specs/features/e2e/reporting_integrity_checks.feature:7'],
  },
  'applicant has NOT uploaded required photo': {
    pattern: /^applicant\ has\ NOT\ uploaded\ required\ photo$/,
    python: 'test/python/steps/integrity_steps.py:32',
    typescript: 'test/typescript/steps/integrity_steps.ts:88',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:8'],
  },
  '"{string}" should be flagged for missing photo': {
    pattern: /^"([^"]*)"\ should\ be\ flagged\ for\ missing\ photo$/,
    python: 'test/python/steps/integrity_steps.py:167',
    typescript: 'test/typescript/steps/integrity_steps.ts:222',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:10'],
  },
  'the integrity report should show the missing upload type': {
    pattern: /^the\ integrity\ report\ should\ show\ the\ missing\ upload\ type$/,
    python: 'test/python/steps/integrity_steps.py:185',
    typescript: 'test/typescript/steps/integrity_steps.ts:233',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:11'],
  },
  'applicant has started TTC application but not submitted': {
    pattern: /^applicant\ has\ started\ TTC\ application\ but\ not\ submitted$/,
    python: 'test/python/steps/integrity_steps.py:51',
    typescript: 'test/typescript/steps/integrity_steps.ts:108',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:14'],
  },
  '"{string}" should be flagged for incomplete application': {
    pattern: /^"([^"]*)"\ should\ be\ flagged\ for\ incomplete\ application$/,
    python: 'test/python/steps/integrity_steps.py:205',
    typescript: 'test/typescript/steps/integrity_steps.ts:251',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:16'],
  },
  'the report should show the application status as "incomplete"': {
    pattern: /^the\ report\ should\ show\ the\ application\ status\ as\ "incomplete"$/,
    python: 'test/python/steps/integrity_steps.py:223',
    typescript: 'test/typescript/steps/integrity_steps.ts:262',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:17'],
  },
  'evaluation was submitted with email "{string}"': {
    pattern: /^evaluation\ was\ submitted\ with\ email\ "([^"]*)"$/,
    python: 'test/python/steps/integrity_steps.py:68',
    typescript: 'test/typescript/steps/integrity_steps.ts:120',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:20'],
  },
  'applicant exists with email "{string}"': {
    pattern: /^applicant\ exists\ with\ email\ "([^"]*)"$/,
    python: 'test/python/steps/integrity_steps.py:83',
    typescript: 'test/typescript/steps/integrity_steps.ts:133',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:21'],
  },
  'the evaluation should be flagged as unmatched': {
    pattern: /^the\ evaluation\ should\ be\ flagged\ as\ unmatched$/,
    python: 'test/python/steps/integrity_steps.py:240',
    typescript: 'test/typescript/steps/integrity_steps.ts:278',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:23'],
  },
  'the report should show the mismatched email': {
    pattern: /^the\ report\ should\ show\ the\ mismatched\ email$/,
    python: 'test/python/steps/integrity_steps.py:256',
    typescript: 'test/typescript/steps/integrity_steps.ts:290',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:24'],
  },
  'I download the integrity report as CSV': {
    pattern: /^I\ download\ the\ integrity\ report\ as\ CSV$/,
    python: 'test/python/steps/integrity_steps.py:138',
    typescript: 'test/typescript/steps/integrity_steps.ts:194',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:28'],
  },
  'the CSV should contain columns: email, flags, missing_uploads, incomplete_forms, mismatches': {
    pattern: /^the\ CSV\ should\ contain\ columns:\ email,\ flags,\ missing_uploads,\ incomplete_forms,\ mismatches$/,
    python: 'test/python/steps/integrity_steps.py:270',
    typescript: 'test/typescript/steps/integrity_steps.ts:301',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:29'],
  },
  'the CSV should be downloadable via admin dashboard': {
    pattern: /^the\ CSV\ should\ be\ downloadable\ via\ admin\ dashboard$/,
    python: 'test/python/steps/integrity_steps.py:282',
    typescript: 'test/typescript/steps/integrity_steps.ts:314',
    features: ['specs/features/e2e/reporting_integrity_checks.feature:30'],
  },
  'test mode is disabled': {
    pattern: /^test\ mode\ is\ disabled$/,
    python: 'test/python/steps/e2e_api_steps.py:548',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:577',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:19'],
  },
  'test mode is enabled': {
    pattern: /^test\ mode\ is\ enabled$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:52'],
  },
  'test mode is disabled (real deadline enforcement)': {
    pattern: /^test\ mode\ is\ disabled\ \(real\ deadline\ enforcement\)$/,
    python: 'test/python/steps/e2e_api_steps.py:560',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:585',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:8'],
  },
  'the TTC application should be marked as submitted': {
    pattern: /^the\ TTC\ application\ should\ be\ marked\ as\ submitted$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:19', 'specs/features/e2e/deadline_and_whitelist_override.feature:54', 'specs/features/e2e/draft_save_and_resume.feature:19'],
  },
  'the form should be marked as complete': {
    pattern: /^the\ form\ should\ be\ marked\ as\ complete$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:20', 'specs/features/e2e/dependent_fields_do_not_break_completeness.feature:16'],
  },
  'the evaluation should be recorded for the applicant': {
    pattern: /^the\ evaluation\ should\ be\ recorded\ for\ the\ applicant$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:32'],
  },
  'the user should be in the whitelist config': {
    pattern: /^the\ user\ should\ be\ in\ the\ whitelist\ config$/,
    python: 'test/python/steps/e2e_api_steps.py:387',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:450',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:24', 'specs/features/e2e/deadline_and_whitelist_override.feature:49'],
  },
  'the applicant should be able to submit within grace period': {
    pattern: /^the\ applicant\ should\ be\ able\ to\ submit\ within\ grace\ period$/,
    python: 'test/python/steps/e2e_api_steps.py:395',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:456',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:25'],
  },
  'the submission should be rejected with deadline error': {
    pattern: /^the\ submission\ should\ be\ rejected\ with\ deadline\ error$/,
    python: 'test/python/steps/e2e_api_steps.py:403',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:465',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:14'],
  },
  'the form should not be marked as submitted': {
    pattern: /^the\ form\ should\ not\ be\ marked\ as\ submitted$/,
    python: 'test/python/steps/e2e_api_steps.py:414',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:475',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:15'],
  },
  'the evaluation should be matched to the applicant': {
    pattern: /^the\ evaluation\ should\ be\ matched\ to\ the\ applicant$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:13'],
  },
  'the evaluation should count toward the applicant\'s evaluation total': {
    pattern: /^the\ evaluation\ should\ count\ toward\ the\ applicant's\ evaluation\ total$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:14', 'specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:28'],
  },
  'the evaluation should be matched via name fallback': {
    pattern: /^the\ evaluation\ should\ be\ matched\ via\ name\ fallback$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:22'],
  },
  'the evaluation should be matched via fuzzy email matching': {
    pattern: /^the\ evaluation\ should\ be\ matched\ via\ fuzzy\ email\ matching$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:30'],
  },
  'the error response should indicate grace period expired': {
    pattern: /^the\ error\ response\ should\ indicate\ grace\ period\ expired$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:38'],
  },
  'the submission should be rejected': {
    pattern: /^the\ submission\ should\ be\ rejected$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:37'],
  },
  'the self-evaluation should be marked as submitted': {
    pattern: /^the\ self\-evaluation\ should\ be\ marked\ as\ submitted$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:19'],
  },
  'the feedback should be linked to the graduate': {
    pattern: /^the\ feedback\ should\ be\ linked\ to\ the\ graduate$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:35'],
  },
  'the summary should show both self-eval and co-teacher feedback': {
    pattern: /^the\ summary\ should\ show\ both\ self\-eval\ and\ co\-teacher\ feedback$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:43'],
  },
  'the user summary should show:': {
    pattern: /^the\ user\ summary\ should\ show:$/,
    python: 'test/python/steps/e2e_api_steps.py:521',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:527',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:45'],
  },
  'the combined report should include both evaluations': {
    pattern: /^the\ combined\ report\ should\ include\ both\ evaluations$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:52'],
  },
  'the whitelist grace period has expired': {
    pattern: /^the\ whitelist\ grace\ period\ has\ expired$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:36'],
  },
  'only teacher 1 email should be in the evaluator list': {
    pattern: /^only\ teacher\ 1\ email\ should\ be\ in\ the\ evaluator\ list$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/dependent_fields_do_not_break_completeness.feature:15'],
  },
  'teacher 1 and 2 emails should be in the evaluator list': {
    pattern: /^teacher\ 1\ and\ 2\ emails\ should\ be\ in\ the\ evaluator\ list$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/dependent_fields_do_not_break_completeness.feature:25'],
  },
  // Parameterized steps - these use {string} and {int} as template placeholders
  // The actual step implementations will handle the parameter values
  'I am authenticated as applicant with email {string}': {
    pattern: /^I\ am\ authenticated\ as\ applicant\ with\ email\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:17',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:145',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:9', 'specs/features/e2e/deadline_and_whitelist_override.feature:10'],
  },
  'I am authenticated as evaluator with email {string}': {
    pattern: /^I\ am\ authenticated\ as\ evaluator\ with\ email\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:23'],
  },
  'I am authenticated as {string}': {
    pattern: /^I\ am\ authenticated\ as\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:51',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:174',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:12', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:27', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:46', 'specs/features/e2e/home_country_changes_available_ttcs.feature:35', 'specs/features/e2e/home_country_changes_available_ttcs.feature:42', 'specs/features/e2e/home_country_changes_available_ttcs.feature:43', 'specs/features/e2e/home_country_changes_available_ttcs.feature:44'],
  },
  'test TTC option {string} is available': {
    pattern: /^test\ TTC\ option\ "([^"]*)"\ is\ available$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:8'],
  },
  'TTC option {string} has display_until in the past': {
    pattern: /^TTC\ option\ "([^"]*)"\ has\ display_until\ in\ the\ past$/,
    python: 'test/python/steps/e2e_api_steps.py:64',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:182',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:10', 'specs/features/e2e/deadline_and_whitelist_override.feature:20', 'specs/features/e2e/deadline_and_whitelist_override.feature:38'],
  },
  'I submit TTC application for {string} with:': {
    pattern: /^I\ submit\ TTC\ application\ for\ "([^"]*)"\ with:$/,
    python: 'test/python/steps/e2e_api_steps.py:93',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:211',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:12'],
  },
  'I submit TTC evaluation for {string} with:': {
    pattern: /^I\ submit\ TTC\ evaluation\ for\ "([^"]*)"\ with:$/,
    python: 'test/python/steps/e2e_api_steps.py:117',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:280',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:27'],
  },
  'I attempt to submit TTC application via API for {string}': {
    pattern: /^I\ attempt\ to\ submit\ TTC\ application\ via\ API\ for\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:138',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:253',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:13'],
  },
  '{string} has completed TTC {string}': {
    pattern: /^"([^"]*)"\ has\ completed\ TTC\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:9'],
  },
  'I submit post-TTC self-evaluation for course starting {string} with:': {
    pattern: /^I\ submit\ post\-TTC\ self\-evaluation\ for\ course\ starting\ "([^"]*)"\ with:$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:13', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:32', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:44'],
  },
  'I submit post-TTC feedback for {string} with:': {
    pattern: /^I\ submit\ post\-TTC\ feedback\ for\ "([^"]*)"\ with:$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:28'],
  },
  'I set my home country to {string} via API': {
    pattern: /^I\ set\ my\ home\ country\ to\ "([^"]*)"\ via\ API$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/home_country_changes_available_ttcs.feature:10'],
  },
  'I add {string} to the whitelist via API': {
    pattern: /^I\ add\ "([^"]*)"\ to\ the\ whitelist\ via\ API$/,
    python: 'test/python/steps/e2e_api_steps.py:250',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:338',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:23', 'specs/features/e2e/deadline_and_whitelist_override.feature:48'],
  },
  'user {string} is NOT whitelisted': {
    pattern: /^user\ "([^"]*)"\ is\ NOT\ whitelisted$/,
    python: 'test/python/steps/e2e_api_steps.py:262',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:347',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:21'],
  },
  'user {string} is whitelisted': {
    pattern: /^user\ "([^"]*)"\ is\ whitelisted$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:40'],
  },
  'I request the combined user application report for {string}': {
    pattern: /^I\ request\ the\ combined\ user\ application\ report\ for\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/ttc_application_to_admin_review.feature:44'],
  },
  'applicant {string} exists with email {string}': {
    pattern: /^applicant\ "([^"]*)"\ exists\ with\ email\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:10'],
  },
  'applicant has submitted TTC application for {string}': {
    pattern: /^applicant\ has\ submitted\ TTC\ application\ for\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:11'],
  },
  'evaluator submits evaluation with candidate email {string} for applicant {string}': {
    pattern: /^evaluator\ submits\ evaluation\ with\ candidate\ email\ "([^"]*)"\ for\ applicant\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:12', 'specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:19', 'specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:24', 'specs/features/e2e/evaluation_matching_tolerates_messy_inputs.feature:29'],
  },
  'I select {string} for "How many evaluating teachers?"': {
    pattern: /^I\ select\ "([^"]*)"\ for\ "How\ many\ evaluating\ teachers\?"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/dependent_fields_do_not_break_completeness.feature:13', 'specs/features/e2e/dependent_fields_do_not_break_completeness.feature:21', 'specs/features/e2e/dependent_fields_do_not_break_completeness.feature:31', 'specs/features/e2e/dependent_fields_do_not_break_completeness.feature:48'],
  },
  'notification should be sent to {string}': {
    pattern: /^notification\ should\ be\ sent\ to\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:20', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:51'],
  },
  '{string} should not be flagged for missing co-teacher feedback': {
    pattern: /^"([^"]*)"\ should\ not\ be\ flagged\ for\ missing\ co\-teacher\ feedback$/,
    python: 'test/python/steps/e2e_api_steps.py:1',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:1',
    features: ['specs/features/e2e/post_ttc_coteaching_cycle.feature:42', 'specs/features/e2e/post_ttc_coteaching_cycle.feature:56'],
  },
  // Draft Save and Resume Steps
  'I fill in the TTC application form partially with:': {
    pattern: /^I\ fill\ in\ the\ TTC\ application\ form\ partially\ with:$/,
    python: 'test/python/steps/draft_steps.py:16',
    typescript: 'test/typescript/steps/draft_steps.ts:42',
    features: ['specs/features/e2e/draft_save_and_resume.feature:8'],
  },
  'I save the application as draft': {
    pattern: /^I\ save\ the\ application\ as\ draft$/,
    python: 'test/python/steps/draft_steps.py:36',
    typescript: 'test/typescript/steps/draft_steps.ts:66',
    features: ['specs/features/e2e/draft_save_and_resume.feature:13'],
  },
  'I should see my draft data persisted': {
    pattern: /^I\ should\ see\ my\ draft\ data\ persisted$/,
    python: 'test/python/steps/draft_steps.py:48',
    typescript: 'test/typescript/steps/draft_steps.ts:74',
    features: ['specs/features/e2e/draft_save_and_resume.feature:17'],
  },
  'I complete the remaining required fields and submit': {
    pattern: /^I\ complete\ the\ remaining\ required\ fields\ and\ submit$/,
    python: 'test/python/steps/draft_steps.py:64',
    typescript: 'test/typescript/steps/draft_steps.ts:88',
    features: ['specs/features/e2e/draft_save_and_resume.feature:18'],
  },
  'I save a partial TTC application as draft': {
    pattern: /^I\ save\ a\ partial\ TTC\ application\ as\ draft$/,
    python: 'test/python/steps/draft_steps.py:98',
    typescript: 'test/typescript/steps/draft_steps.ts:114',
    features: ['specs/features/e2e/draft_save_and_resume.feature:23'],
  },
  'I save a partial evaluator profile as draft': {
    pattern: /^I\ save\ a\ partial\ evaluator\ profile\ as\ draft$/,
    python: 'test/python/steps/draft_steps.py:116',
    typescript: 'test/typescript/steps/draft_steps.ts:127',
    features: ['specs/features/e2e/draft_save_and_resume.feature:24'],
  },
  'I navigate to the TTC application form': {
    pattern: /^I\ navigate\ to\ the\ TTC\ application\ form$/,
    python: 'test/python/steps/e2e_api_steps.py:565',
    typescript: 'test/typescript/steps/draft_steps.ts:141',
    features: ['specs/features/e2e/deadline_and_whitelist_override.feature:11', 'specs/features/e2e/dependent_fields_do_not_break_completeness.feature:10', 'specs/features/e2e/draft_save_and_resume.feature:25'],
  },
  'I should see the TTC application draft data': {
    pattern: /^I\ should\ see\ the\ TTC\ application\ draft\ data$/,
    python: 'test/python/steps/draft_steps.py:141',
    typescript: 'test/typescript/steps/draft_steps.ts:149',
    features: ['specs/features/e2e/draft_save_and_resume.feature:26'],
  },
  'I navigate to the evaluator profile form': {
    pattern: /^I\ navigate\ to\ the\ evaluator\ profile\ form$/,
    python: 'test/python/steps/draft_steps.py:156',
    typescript: 'test/typescript/steps/draft_steps.ts:160',
    features: ['specs/features/e2e/draft_save_and_resume.feature:27'],
  },
  'I should see the evaluator profile draft data': {
    pattern: /^I\ should\ see\ the\ evaluator\ profile\ draft\ data$/,
    python: 'test/python/steps/draft_steps.py:162',
    typescript: 'test/typescript/steps/draft_steps.ts:164',
    features: ['specs/features/e2e/draft_save_and_resume.feature:28'],
  },
  'I open the TTC application form': {
    pattern: /^I\ open\ the\ TTC\ application\ form$/,
    python: 'test/python/steps/draft_steps.py:96',
    typescript: 'test/typescript/steps/draft_steps.ts:145',
    features: ['specs/features/e2e/draft_save_and_resume.feature:16'],
  },
  // Validation Error Steps
  'I submit the TTC application form with missing required fields:': {
    pattern: /^I\ submit\ the\ TTC\ application\ form\ with\ missing\ required\ fields:$/,
    python: 'test/python/steps/validation_steps.py:20',
    typescript: 'test/typescript/steps/validation_steps.ts:38',
    features: ['specs/features/e2e/validation_errors.feature:11'],
  },
  'I should see field-level errors': {
    pattern: /^I\ should\ see\ field\-level\ errors$/,
    python: 'test/python/steps/validation_steps.py:54',
    typescript: 'test/typescript/steps/validation_steps.ts:77',
    features: ['specs/features/e2e/validation_errors.feature:17'],
  },
  'the submission should be blocked': {
    pattern: /^the\ submission\ should\ be\ blocked$/,
    python: 'test/python/steps/validation_steps.py:61',
    typescript: 'test/typescript/steps/validation_steps.ts:88',
    features: ['specs/features/e2e/validation_errors.feature:18', 'specs/features/e2e/validation_errors.feature:25'],
  },
  'my draft data should remain intact': {
    pattern: /^my\ draft\ data\ should\ remain\ intact$/,
    python: 'test/python/steps/validation_steps.py:72',
    typescript: 'test/typescript/steps/validation_steps.ts:103',
    features: ['specs/features/e2e/validation_errors.feature:19'],
  },
  'I submit the TTC application with an invalid email format': {
    pattern: /^I\ submit\ the\ TTC\ application\ with\ an\ invalid\ email\ format$/,
    python: 'test/python/steps/validation_steps.py:82',
    typescript: 'test/typescript/steps/validation_steps.ts:123',
    features: ['specs/features/e2e/validation_errors.feature:22'],
  },
  'I should see an email format validation error': {
    pattern: /^I\ should\ see\ an\ email\ format\ validation\ error$/,
    python: 'test/python/steps/validation_steps.py:99',
    typescript: 'test/typescript/steps/validation_steps.ts:142',
    features: ['specs/features/e2e/validation_errors.feature:24'],
  },
  'I should see {string} error message': {
    pattern: /^I\ should\ see\ "([^"]*)"\ error\ message$/,
    python: 'test/python/steps/validation_steps.py:111',
    typescript: 'test/typescript/steps/validation_steps.ts:156',
    features: ['specs/features/e2e/validation_errors.feature:33'],
  },
  'I attempt to submit the TTC application': {
    pattern: /^I\ attempt\ to\ submit\ the\ TTC\ application$/,
    python: 'test/python/steps/e2e_api_steps.py:138',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:253',
    features: ['specs/features/e2e/validation_errors.feature:31'],
  },
  // Certificate Generation Gated by Completion Steps
  'applicant has completed all TTC requirements:': {
    pattern: /^applicant\ has\ completed\ all\ TTC\ requirements:$/,
    python: 'test/python/steps/certificate_steps.py:140',
    typescript: 'test/typescript/steps/certificate_steps.ts:426',
    features: ['specs/features/e2e/certificate_gating.feature:7'],
  },
  'applicant has only 1 evaluation (requires 2)': {
    pattern: /^applicant\ has\ only\ 1\ evaluation\ \(requires\ 2\)$/,
    python: 'test/python/steps/certificate_steps.py:169',
    typescript: 'test/typescript/steps/certificate_steps.ts:463',
    features: ['specs/features/e2e/certificate_gating.feature:21'],
  },
  'applicant has completed TTC and evaluations': {
    pattern: /^applicant\ has\ completed\ TTC\ and\ evaluations$/,
    python: 'test/python/steps/certificate_steps.py:181',
    typescript: 'test/typescript/steps/certificate_steps.ts:476',
    features: ['specs/features/e2e/certificate_gating.feature:28'],
  },
  'post-TTC co-teacher feedback is missing': {
    pattern: /^post\-TTC\ co\-teacher\ feedback\ is\ missing$/,
    python: 'test/python/steps/certificate_steps.py:193',
    typescript: 'test/typescript/steps/certificate_steps.ts:489',
    features: ['specs/features/e2e/certificate_gating.feature:29'],
  },
  'I request a certificate PDF for {string}': {
    pattern: /^I\ request\ a\ certificate\ PDF\ for\ "([^"]*)"$/,
    python: 'test/python/steps/certificate_steps.py:204',
    typescript: 'test/typescript/steps/certificate_steps.ts:501',
    features: ['specs/features/e2e/certificate_gating.feature:14,23,30'],
  },
  'the certificate should include the applicant\'s name': {
    pattern: /^the\ certificate\ should\ include\ the\ applicant's\ name$/,
    python: 'test/python/steps/certificate_steps.py:275',
    typescript: 'test/typescript/steps/certificate_steps.ts:571',
    features: ['specs/features/e2e/certificate_gating.feature:16'],
  },
  'the certificate should include the TTC completion date': {
    pattern: /^the\ certificate\ should\ include\ the\ TTC\ completion\ date$/,
    python: 'test/python/steps/certificate_steps.py:288',
    typescript: 'test/typescript/steps/certificate_steps.ts:590',
    features: ['specs/features/e2e/certificate_gating.feature:17'],
  },
  'certificate generation should be blocked': {
    pattern: /^certificate\ generation\ should\ be\ blocked$/,
    python: 'test/python/steps/certificate_steps.py:301',
    typescript: 'test/typescript/steps/certificate_steps.ts:609',
    features: ['specs/features/e2e/certificate_gating.feature:24,31'],
  },
  'I should see the reason: {string}': {
    pattern: /^I\ should\ see\ the\ reason:\ "([^"]*)"$/,
    python: 'test/python/steps/certificate_steps.py:318',
    typescript: 'test/typescript/steps/certificate_steps.ts:636',
    features: ['specs/features/e2e/certificate_gating.feature:25,32'],
  },
  // Full Evaluator Workflow Steps - TASK-E2E-009
  'applicant "{string}" has submitted TTC application for "{string}"': {
    pattern: /^applicant\ "([^"]*)"\ has\ submitted\ TTC\ application\ for\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:646',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:708',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:7'],
  },
  'applicant has uploaded photo and required documents': {
    pattern: /^applicant\ has\ uploaded\ photo\ and\ required\ documents$/,
    python: 'test/python/steps/e2e_api_steps.py:665',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:730',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:8'],
  },
  'I open the TTC evaluation form for "{string}"': {
    pattern: /^I\ open\ the\ TTC\ evaluation\ form\ for\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:688',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:753',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:10'],
  },
  'I should see the applicant\'s submitted application data': {
    pattern: /^I\ should\ see\ the\ applicant\'s\ submitted\ application\ data$/,
    python: 'test/python/steps/e2e_api_steps.py:703',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:768',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:11'],
  },
  'I should see the applicant\'s uploaded photo': {
    pattern: /^I\ should\ see\ the\ applicant\'s\ uploaded\ photo$/,
    python: 'test/python/steps/e2e_api_steps.py:716',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:782',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:12'],
  },
  'I should see the applicant\'s uploaded documents': {
    pattern: /^I\ should\ see\ the\ applicant\'s\ uploaded\ documents$/,
    python: 'test/python/steps/e2e_api_steps.py:730',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:796',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:13'],
  },
  'I submit the evaluation with:': {
    pattern: /^I\ submit\ the\ evaluation\ with:$/,
    python: 'test/python/steps/e2e_api_steps.py:744',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:810',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:14'],
  },
  'the evaluation status should update to "{string}"': {
    pattern: /^the\ evaluation\ status\ should\ update\ to\ "([^"]*)"$/,
    python: 'test/python/steps/e2e_api_steps.py:772',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:839',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:18'],
  },
  'the applicant should see the evaluation in their portal': {
    pattern: /^the\ applicant\ should\ see\ the\ evaluation\ in\ their\ portal$/,
    python: 'test/python/steps/e2e_api_steps.py:784',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:852',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:19'],
  },
  'evaluator A has submitted an evaluation for applicant': {
    pattern: /^evaluator\ A\ has\ submitted\ an\ evaluation\ for\ applicant$/,
    python: 'test/python/steps/e2e_api_steps.py:799',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:868',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:22'],
  },
  'I am authenticated as evaluator B': {
    pattern: /^I\ am\ authenticated\ as\ evaluator\ B$/,
    python: 'test/python/steps/e2e_api_steps.py:818',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:888',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:23'],
  },
  'I view the applicant\'s evaluation summary': {
    pattern: /^I\ view\ the\ applicant\'s\ evaluation\ summary$/,
    python: 'test/python/steps/e2e_api_steps.py:828',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:899',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:24'],
  },
  'I should NOT see evaluator A\'s private evaluation notes': {
    pattern: /^I\ should\ NOT\ see\ evaluator\ A\'s\ private\ evaluation\ notes$/,
    python: 'test/python/steps/e2e_api_steps.py:845',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:917',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:25'],
  },
  'I should see that an evaluation was submitted': {
    pattern: /^I\ should\ see\ that\ an\ evaluation\ was\ submitted$/,
    python: 'test/python/steps/e2e_api_steps.py:860',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:933',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:26'],
  },
  'I attempt to access evaluation for unassigned applicant': {
    pattern: /^I\ attempt\ to\ access\ evaluation\ for\ unassigned\ applicant$/,
    python: 'test/python/steps/e2e_api_steps.py:875',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:949',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:30'],
  },
  'I should see "{string}" or "{string}" error': {
    pattern: /^I\ should\ see\ "([^"]*)"\ or\ "([^"]*)"\ error$/,
    python: 'test/python/steps/e2e_api_steps.py:887',
    typescript: 'test/typescript/steps/e2e_api_steps.ts:962',
    features: ['specs/features/e2e/full_evaluator_workflow.feature:31'],
  },
  // Form Prerequisites and Conditional Availability Steps - TASK-E2E-012
  // Note: 'I am authenticated as applicant with email {string}' already exists in e2e_api_steps
  'I have NOT completed the Happiness Program': {
    pattern: /^I\ have\ NOT\ completed\ the\ Happiness\ Program$/,
    python: 'test/python/steps/form_prerequisites_steps.py:53',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:95',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:8', 'specs/features/e2e/form_prerequisites_conditional.feature:22', 'specs/features/e2e/course_eligibility_by_profile.feature:19', 'specs/features/e2e/course_eligibility_by_profile.feature:25'],
  },
  'the DSN application form should NOT be available': {
    pattern: /^the\ DSN\ application\ form\ should\ NOT\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:62',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:104',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:9'],
  },
  'I complete the Happiness Program': {
    pattern: /^I\ complete\ the\ Happiness\ Program$/,
    python: 'test/python/steps/form_prerequisites_steps.py:71',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:113',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:10', 'specs/features/e2e/form_prerequisites_conditional.feature:24', 'specs/features/e2e/course_eligibility_by_profile.feature:27'],
  },
  'the DSN application form should become available': {
    pattern: /^the\ DSN\ application\ form\ should\ become\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:81',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:120',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:11'],
  },
  'I have completed Part 1 but NOT Part 2': {
    pattern: /^I\ have\ completed\ Part\ 1\ but\ NOT\ Part\ 2$/,
    python: 'test/python/steps/form_prerequisites_steps.py:91',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:133',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:15'],
  },
  'the YES+ application form should NOT be available': {
    pattern: /^the\ YES\+\ application\ form\ should\ NOT\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:102',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:142',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:16'],
  },
  'I complete Part 2': {
    pattern: /^I\ complete\ Part\ 2$/,
    python: 'test/python/steps/form_prerequisites_steps.py:110',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:152',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:17'],
  },
  'the YES+ application form should become available': {
    pattern: /^the\ YES\+\ application\ form\ should\ become\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:119',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:159',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:18'],
  },
  'the Part 1 course application should NOT be available': {
    pattern: /^the\ Part\ 1\ course\ application\ should\ NOT\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:131',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:175',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:23'],
  },
  'the Part 1 course application should become available': {
    pattern: /^the\ Part\ 1\ course\ application\ should\ become\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:139',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:185',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:25'],
  },
  'I have NOT completed Part 1': {
    pattern: /^I\ have\ NOT\ completed\ Part\ 1$/,
    python: 'test/python/steps/form_prerequisites_steps.py:149',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:198',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:29'],
  },
  'the Part 2 course application should NOT be available': {
    pattern: /^the\ Part\ 2\ course\ application\ should\ NOT\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:160',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:207',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:30'],
  },
  'I complete Part 1': {
    pattern: /^I\ complete\ Part\ 1$/,
    python: 'test/python/steps/form_prerequisites_steps.py:168',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:217',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:31'],
  },
  'the Part 2 course application should become available': {
    pattern: /^the\ Part\ 2\ course\ application\ should\ become\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:177',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:224',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:32'],
  },
  'my home country is {string}': {
    pattern: /^my\ home\ country\ is\ "([^"]*)"$/,
    python: 'test/python/steps/form_prerequisites_steps.py:187',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:237',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:36'],
  },
  'US-specific TTC options should be available': {
    pattern: /^US\-specific\ TTC\ options\ should\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:198',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:247',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:37'],
  },
  'India-specific TTC options should NOT be available': {
    pattern: /^India\-specific\ TTC\ options\ should\ NOT\ be\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:209',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:261',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:38'],
  },
  'I update my home country to {string}': {
    pattern: /^I\ update\ my\ home\ country\ to\ "([^"]*)"$/,
    python: 'test/python/steps/form_prerequisites_steps.py:219',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:274',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:39'],
  },
  'India-specific TTC options should become available': {
    pattern: /^India\-specific\ TTC\ options\ should\ become\ available$/,
    python: 'test/python/steps/form_prerequisites_steps.py:227',
    typescript: 'test/typescript/steps/form_prerequisites_steps.ts:280',
    features: ['specs/features/e2e/form_prerequisites_conditional.feature:40'],
  },
  // Course Eligibility by User Profile Steps - TASK-E2E-013
  'I view my course eligibility dashboard': {
    pattern: /^I\ view\ my\ course\ eligibility\ dashboard$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:93',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:101',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:8'],
  },
  'I should see a list of available courses with prerequisites:': {
    pattern: /^I\ should\ see\ a\ list\ of\ available\ courses\ with\ prerequisites:$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:102',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:108',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:9'],
  },
  'I attempt to access the DSN application form': {
    pattern: /^I\ attempt\ to\ access\ the\ DSN\ application\ form$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:133',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:155',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:20'],
  },
  'I should see "not available" message': {
    pattern: /^I\ should\ see\ "not\ available"\ message$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:159',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:179',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:21'],
  },
  'the message should explain the prerequisite: {string}': {
    pattern: /^the\ message\ should\ explain\ the\ prerequisite:\ "([^"]*)"$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:173',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:200',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:22'],
  },
  'the DSN form shows as "not available"': {
    pattern: /^the\ DSN\ form\ shows\ as\ "not\ available"$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:188',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:232',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:26'],
  },
  'I refresh the eligibility dashboard': {
    pattern: /^I\ refresh\ the\ eligibility\ dashboard$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:201',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:245',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:28'],
  },
  'the DSN form should show as "available"': {
    pattern: /^the\ DSN\ form\ should\ show\ as\ "available"$/,
    python: 'test/python/steps/eligibility_dashboard_steps.py:211',
    typescript: 'test/typescript/steps/eligibility_dashboard_steps.ts:251',
    features: ['specs/features/e2e/course_eligibility_by_profile.feature:29'],
  },
  // TEST ENTRY - validates placeholder matching when pattern field is absent
  // This entry intentionally has NO pattern field to test the fallback placeholder logic
  'test placeholder step with value {string}': {
    python: 'test/python/steps/test_steps.py:21',
    typescript: 'test/typescript/steps/test_steps.ts:18',
    features: ['specs/features/test/placeholder_matching.feature:10'],
  },
  'test placeholder step with float {float}': {
    python: 'test/python/steps/test_steps.py:27',
    typescript: 'test/typescript/steps/test_steps.ts:23',
    features: ['specs/features/test/placeholder_matching.feature:23'],
  },
  'test placeholder step with int {int}': {
    python: 'test/python/steps/test_steps.py:33',
    typescript: 'test/typescript/steps/test_steps.ts:28',
    features: ['specs/features/test/placeholder_matching.feature:19'],
  },
  'I have a registry entry with placeholder but no pattern': {
    pattern: /^I\ have\ a\ registry\ entry\ with\ placeholder\ but\ no\ pattern$/,
    python: 'test/python/steps/test_steps.py:7',
    typescript: 'test/typescript/steps/test_steps.ts:7',
    features: ['specs/features/test/placeholder_matching.feature:5,10'],
  },
  'the alignment check runs': {
    pattern: /^the\ alignment\ check\ runs$/,
    python: 'test/python/steps/test_steps.py:13',
    typescript: 'test/typescript/steps/test_steps.ts:10',
    features: ['specs/features/test/placeholder_matching.feature:6,11'],
  },
  'the step should match correctly': {
    pattern: /^the\ step\ should\ match\ correctly$/,
    python: 'test/python/steps/test_steps.py:19',
    typescript: 'test/typescript/steps/test_steps.ts:14',
    features: ['specs/features/test/placeholder_matching.feature:7,12'],
  },
  'this step should be detected as a dead step': {
    pattern: /^this\ step\ should\ be\ detected\ as\ a\ dead\ step$/,
    python: 'test/python/steps/test_steps.py:25',
    typescript: 'test/typescript/steps/test_steps.ts:20',
    features: ['specs/features/test/asterisk-step.feature:6'],
  },
  // Upload API Authentication Steps - TASK-074
  'I am in platform auth mode': {
    pattern: /^I\ am\ in\ platform\ auth\ mode$/,
    python: 'test/python/steps/auth_steps.py:181',
    typescript: 'test/typescript/steps/auth_steps.ts:119',
    features: ['specs/features/auth/upload_api_auth.feature:9', 'specs/features/auth/upload_api_auth.feature:15', 'specs/features/auth/upload_api_auth.feature:20'],
  },
  'I have a valid user email {string}': {
    pattern: /^I\ have\ a\ valid\ user\ email\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:187',
    typescript: 'test/typescript/steps/auth_steps.ts:126',
    features: ['specs/features/auth/upload_api_auth.feature:10', 'specs/features/auth/upload_api_auth.feature:44', 'specs/features/auth/upload_api_auth.feature:50', 'specs/features/auth/upload_api_auth.feature:86'],
  },
  'I call getAuthenticatedUser with x-user-email header {string}': {
    pattern: /^I\ call\ getAuthenticatedUser\ with\ x-user-email\ header\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:192',
    typescript: 'test/typescript/steps/auth_steps.ts:132',
    features: ['specs/features/auth/upload_api_auth.feature:11', 'specs/features/auth/upload_api_auth.feature:22'],
  },
  'the response should be the user {string}': {
    pattern: /^the\ response\ should\ be\ the\ user\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:267',
    typescript: 'test/typescript/steps/auth_steps.ts:233',
    features: ['specs/features/auth/upload_api_auth.feature:12', 'specs/features/auth/upload_api_auth.feature:33'],
  },
  'I call getAuthenticatedUser without x-user-email header': {
    pattern: /^I\ call\ getAuthenticatedUser\ without\ x-user-email\ header$/,
    python: 'test/python/steps/auth_steps.py:198',
    typescript: 'test/typescript/steps/auth_steps.ts:144',
    features: ['specs/features/auth/upload_api_auth.feature:16'],
  },
  'the response should be null': {
    pattern: /^the\ response\ should\ be\ null$/,
    python: 'test/python/steps/auth_steps.py:273',
    typescript: 'test/typescript/steps/auth_steps.ts:238',
    features: ['specs/features/auth/upload_api_auth.feature:17', 'specs/features/auth/upload_api_auth.feature:29', 'specs/features/auth/upload_api_auth.feature:37', 'specs/features/auth/upload_api_auth.feature:43', 'specs/features/auth/upload_api_auth.feature:51'],
  },
  'I am in session auth mode': {
    pattern: /^I\ am\ in\ session\ auth\ mode$/,
    python: 'test/python/steps/auth_steps.py:186',
    typescript: 'test/typescript/steps/auth_steps.ts:124',
    features: ['specs/features/auth/upload_api_auth.feature:26', 'specs/features/auth/upload_api_auth.feature:31', 'specs/features/auth/upload_api_auth.feature:36', 'specs/features/auth/upload_api_auth.feature:40', 'specs/features/auth/upload_api_auth.feature:46', 'specs/features/auth/upload_api_auth.feature:55'],
  },
  'I have a valid session token for {string}': {
    pattern: /^I\ have\ a\ valid\ session\ token\ for\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:190',
    typescript: 'test/typescript/steps/auth_steps.ts:129',
    features: ['specs/features/auth/upload_api_auth.feature:27', 'specs/features/auth/upload_api_auth.feature:85'],
  },
  'I call getAuthenticatedUser with bearer token': {
    pattern: /^I\ call\ getAuthenticatedUser\ with\ bearer\ token$/,
    python: 'test/python/steps/auth_steps.py:204',
    typescript: 'test/typescript/steps/auth_steps.ts:177',
    features: ['specs/features/auth/upload_api_auth.feature:28', 'specs/features/auth/upload_api_auth.feature:56'],
  },
  'I call getAuthenticatedUser with bearer token {string}': {
    pattern: /^I\ call\ getAuthenticatedUser\ with\ bearer\ token\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:209',
    typescript: 'test/typescript/steps/auth_steps.ts:185',
    features: ['specs/features/auth/upload_api_auth.feature:32'],
  },
  'I call getAuthenticatedUser without authorization header': {
    pattern: /^I\ call\ getAuthenticatedUser\ without\ authorization\ header$/,
    python: 'test/python/steps/auth_steps.py:214',
    typescript: 'test/typescript/steps/auth_steps.ts:194',
    features: ['specs/features/auth/upload_api_auth.feature:37'],
  },
  'I call getAuthenticatedUser with x-user-email header {string} and no bearer token': {
    pattern: /^I\ call\ getAuthenticatedUser\ with\ x-user-email\ header\ "([^"]*)"\ and\ no\ bearer\ token$/,
    python: 'test/python/steps/auth_steps.py:219',
    typescript: 'test/typescript/steps/auth_steps.ts:204',
    features: ['specs/features/auth/upload_api_auth.feature:42'],
  },
  'I have an expired session token for {string}': {
    pattern: /^I\ have\ an\ expired\ session\ token\ for\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:194',
    typescript: 'test/typescript/steps/auth_steps.ts:136',
    features: ['specs/features/auth/upload_api_auth.feature:47'],
  },
  'I have a tampered session token for {string}': {
    pattern: /^I\ have\ a\ tampered\ session\ token\ for\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:199',
    typescript: 'test/typescript/steps/auth_steps.ts:153',
    features: ['specs/features/auth/upload_api_auth.feature:52'],
  },
  'I generate a session token for {string}': {
    pattern: /^I\ generate\ a\ session\ token\ for\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:224',
    typescript: 'test/typescript/steps/auth_steps.ts:215',
    features: ['specs/features/auth/upload_api_auth.feature:58'],
  },
  'the token should have a valid format': {
    pattern: /^the\ token\ should\ have\ a\ valid\ format$/,
    python: 'test/python/steps/auth_steps.py:279',
    typescript: 'test/typescript/steps/auth_steps.ts:243',
    features: ['specs/features/auth/upload_api_auth.feature:59'],
  },
  'I generated a session token for {string}': {
    pattern: /^I\ generated\ a\ session\ token\ for\ "([^"]*)"$/,
    python: 'test/python/steps/auth_steps.py:285',
    typescript: 'test/typescript/steps/auth_steps.ts:129',
    features: ['specs/features/auth/upload_api_auth.feature:60'],
  },
  'I verify the session token': {
    pattern: /^I\ verify\ the\ session\ token$/,
    python: 'test/python/steps/auth_steps.py:229',
    typescript: 'test/typescript/steps/auth_steps.ts:224',
    features: ['specs/features/auth/upload_api_auth.feature:61'],
  },
  'I create a deterministic PDF with default config': {
    pattern: /^I\ create\ a\ deterministic\ PDF\ with\ default\ config$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:55',
    features: ['specs/features/test/deterministic_pdf.feature:7'],
  },
  'I create another deterministic PDF with default config': {
    pattern: /^I\ create\ another\ deterministic\ PDF\ with\ default\ config$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:64',
    features: ['specs/features/test/deterministic_pdf.feature:8'],
  },
  'the PDFs should have identical content hashes': {
    pattern: /^the\ PDFs\ should\ have\ identical\ content\ hashes$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:100',
    features: ['specs/features/test/deterministic_pdf.feature:9'],
  },
  'the PDFs should have identical creation dates': {
    pattern: /^the\ PDFs\ should\ have\ identical\ creation\ dates$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:115',
    features: ['specs/features/test/deterministic_pdf.feature:10,21'],
  },
  'the PDFs should have identical file IDs': {
    pattern: /^the\ PDFs\ should\ have\ identical\ file\ IDs$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:130',
    features: ['specs/features/test/deterministic_pdf.feature:11'],
  },
  'I create a deterministic PDF with custom creation date {string}': {
    pattern: /^I\ create\ a\ deterministic\ PDF\ with\ custom\ creation\ date\ "([^"]*)"$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:73',
    features: ['specs/features/test/deterministic_pdf.feature:14'],
  },
  'I create a deterministic PDF with custom file ID {string}': {
    pattern: /^I\ create\ a\ deterministic\ PDF\ with\ custom\ file\ ID\ "([^"]*)"$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:82',
    features: ['specs/features/test/deterministic_pdf.feature:15'],
  },
  'the PDF creation date should contain {string}': {
    pattern: /^the\ PDF\ creation\ date\ should\ contain\ "([^"]*)"$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:145',
    features: ['specs/features/test/deterministic_pdf.feature:16'],
  },
  'the PDF file ID should be {string}': {
    pattern: /^the\ PDF\ file\ ID\ should\ be\ "([^"]*)"$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:158',
    features: ['specs/features/test/deterministic_pdf.feature:17'],
  },
  'I create a PDF with file ID {string}': {
    pattern: /^I\ create\ a\ PDF\ with\ file\ ID\ "([^"]*)"$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:91',
    features: ['specs/features/test/deterministic_pdf.feature:20,22'],
  },
  'the PDFs should have different file IDs': {
    pattern: /^the\ PDFs\ should\ have\ different\ file\ IDs$/,
    typescript: 'test/typescript/steps/deterministic_pdf_steps.ts:171',
    features: ['specs/features/test/deterministic_pdf.feature:23'],
  },
} as const;
