export const STEPS = {
  'I am authenticated as a Sahaj TTC graduate': {
    pattern: /^I\ am\ authenticated\ as\ a\ Sahaj\ TTC\ graduate$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:8', 'specs/features/forms/post_sahaj_ttc_feedback.feature:8'],
  },
  'I am authenticated as a TTC admin': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ admin$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_portal_settings.feature:8'],
  },
  'I am authenticated as a TTC applicant': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ applicant$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_application_us.feature:8', 'specs/features/forms/ttc_application_non_us.feature:8', 'specs/features/forms/ttc_applicant_profile.feature:8', 'specs/features/forms/dsn_application.feature:8'],
  },
  'I am authenticated as a TTC graduate': {
    pattern: /^I\ am\ authenticated\ as\ a\ TTC\ graduate$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_ttc_self_eval.feature:8', 'specs/features/forms/post_ttc_feedback.feature:8'],
  },
  'I am authenticated as a non-admin user': {
    pattern: /^I\ am\ authenticated\ as\ a\ non\-admin\ user$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/permissions.feature:8'],
  },
  'I am authenticated as an admin user': {
    pattern: /^I\ am\ authenticated\ as\ an\ admin\ user$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/access.feature:8', 'specs/features/admin/reports_pages.feature:8', 'specs/features/admin/settings.feature:8', 'specs/features/user/reporting_get_form_data.feature:8', 'specs/features/reports/user_summary.feature:8', 'specs/features/reports/user_summary.feature:14', 'specs/features/reports/user_integrity.feature:8', 'specs/features/reports/user_integrity.feature:14', 'specs/features/reports/user_integrity.feature:20', 'specs/features/reports/user_report.feature:8', 'specs/features/reports/user_report.feature:14', 'specs/features/reports/user_report.feature:20', 'specs/features/reports/print_form.feature:8', 'specs/features/reports/participant_list.feature:8'],
  },
  'I am authenticated as an evaluator': {
    pattern: /^I\ am\ authenticated\ as\ an\ evaluator$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_evaluation.feature:8', 'specs/features/forms/ttc_evaluator_profile.feature:8'],
  },
  'I am authenticated on the TTC portal': {
    pattern: /^I\ am\ authenticated\ on\ the\ TTC\ portal$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/logout.feature:8', 'specs/features/portal/home.feature:8', 'specs/features/portal/tabs.feature:8', 'specs/features/uploads/photo_upload.feature:8', 'specs/features/uploads/document_upload.feature:8', 'specs/features/api/upload_form.feature:8', 'specs/features/user/form_data_upload.feature:8', 'specs/features/user/config_management.feature:8', 'specs/features/user/config_management.feature:14', 'specs/features/reports/certificate.feature:8'],
  },
  'I am on the TTC portal login page': {
    pattern: /^I\ am\ on\ the\ TTC\ portal\ login\ page$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/login.feature:8', 'specs/features/auth/password_reset.feature:8'],
  },
  'I have multiple form instances for a form type': {
    pattern: /^I\ have\ multiple\ form\ instances\ for\ a\ form\ type$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_instances.feature:8'],
  },
  'I have previously saved form data for a form instance': {
    pattern: /^I\ have\ previously\ saved\ form\ data\ for\ a\ form\ instance$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_data.feature:8'],
  },
  'I open a printable form page': {
    pattern: /^I\ open\ a\ printable\ form\ page$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/print_form.feature:9'],
  },
  'I open an admin-only page': {
    pattern: /^I\ open\ an\ admin\-only\ page$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/permissions.feature:9'],
  },
  'I open the DSN application form': {
    pattern: /^I\ open\ the\ DSN\ application\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/dsn_application.feature:9'],
  },
  'I open the TTC applicant profile form': {
    pattern: /^I\ open\ the\ TTC\ applicant\ profile\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_applicant_profile.feature:9'],
  },
  'I open the TTC application form for a non-US country': {
    pattern: /^I\ open\ the\ TTC\ application\ form\ for\ a\ non\-US\ country$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_application_non_us.feature:9'],
  },
  'I open the TTC application form for the United States': {
    pattern: /^I\ open\ the\ TTC\ application\ form\ for\ the\ United\ States$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_application_us.feature:9'],
  },
  'I open the TTC evaluation form': {
    pattern: /^I\ open\ the\ TTC\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_evaluation.feature:9'],
  },
  'I open the TTC evaluator profile form': {
    pattern: /^I\ open\ the\ TTC\ evaluator\ profile\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_evaluator_profile.feature:9'],
  },
  'I open the TTC portal home': {
    pattern: /^I\ open\ the\ TTC\ portal\ home$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/home.feature:9'],
  },
  'I open the TTC portal settings form': {
    pattern: /^I\ open\ the\ TTC\ portal\ settings\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_portal_settings.feature:9'],
  },
  'I open the admin dashboard page': {
    pattern: /^I\ open\ the\ admin\ dashboard\ page$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/access.feature:9'],
  },
  'I open the admin reports list page': {
    pattern: /^I\ open\ the\ admin\ reports\ list\ page$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/reports_pages.feature:9'],
  },
  'I open the admin settings page': {
    pattern: /^I\ open\ the\ admin\ settings\ page$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/settings.feature:9'],
  },
  'I open the post-Sahaj TTC feedback form': {
    pattern: /^I\ open\ the\ post\-Sahaj\ TTC\ feedback\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_sahaj_ttc_feedback.feature:9'],
  },
  'I open the post-Sahaj TTC self evaluation form': {
    pattern: /^I\ open\ the\ post\-Sahaj\ TTC\ self\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:9'],
  },
  'I open the post-TTC feedback form': {
    pattern: /^I\ open\ the\ post\-TTC\ feedback\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_ttc_feedback.feature:9'],
  },
  'I open the post-TTC self evaluation form': {
    pattern: /^I\ open\ the\ post\-TTC\ self\ evaluation\ form$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_ttc_self_eval.feature:9'],
  },
  'I request a certificate PDF': {
    pattern: /^I\ request\ a\ certificate\ PDF$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/certificate.feature:9'],
  },
  'I request a password reset for my Google account': {
    pattern: /^I\ request\ a\ password\ reset\ for\ my\ Google\ account$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/password_reset.feature:9'],
  },
  'I request a signed upload URL for a document': {
    pattern: /^I\ request\ a\ signed\ upload\ URL\ for\ a\ document$/,
    python: 'test/python/steps/uploads_steps.py:1',
    typescript: 'test/typescript/steps/uploads_steps.ts:1',
    features: ['specs/features/uploads/document_upload.feature:9'],
  },
  'I request a signed upload URL for a profile photo': {
    pattern: /^I\ request\ a\ signed\ upload\ URL\ for\ a\ profile\ photo$/,
    python: 'test/python/steps/uploads_steps.py:1',
    typescript: 'test/typescript/steps/uploads_steps.ts:1',
    features: ['specs/features/uploads/photo_upload.feature:9'],
  },
  'I request a tab template page': {
    pattern: /^I\ request\ a\ tab\ template\ page$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/tabs.feature:9'],
  },
  'I request form data for a specific user via reporting': {
    pattern: /^I\ request\ form\ data\ for\ a\ specific\ user\ via\ reporting$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/reporting_get_form_data.feature:9'],
  },
  'I request my user configuration': {
    pattern: /^I\ request\ my\ user\ configuration$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/config_management.feature:9'],
  },
  'I request that form data': {
    pattern: /^I\ request\ that\ form\ data$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_data.feature:9'],
  },
  'I request the combined user application report': {
    pattern: /^I\ request\ the\ combined\ user\ application\ report$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:15'],
  },
  'I request the list of form instances': {
    pattern: /^I\ request\ the\ list\ of\ form\ instances$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_instances.feature:9'],
  },
  'I request the participant list report': {
    pattern: /^I\ request\ the\ participant\ list\ report$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/participant_list.feature:9'],
  },
  'I request the user application report as HTML': {
    pattern: /^I\ request\ the\ user\ application\ report\ as\ HTML$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:9'],
  },
  'I request the user application report as forms': {
    pattern: /^I\ request\ the\ user\ application\ report\ as\ forms$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:21'],
  },
  'I request the user integrity report by user': {
    pattern: /^I\ request\ the\ user\ integrity\ report\ by\ user$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:15'],
  },
  'I request the user summary report by user': {
    pattern: /^I\ request\ the\ user\ summary\ report\ by\ user$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_summary.feature:15'],
  },
  'I run the user integrity postload job': {
    pattern: /^I\ run\ the\ user\ integrity\ postload\ job$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:21'],
  },
  'I run the user integrity report load job': {
    pattern: /^I\ run\ the\ user\ integrity\ report\ load\ job$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:9'],
  },
  'I run the user summary report load job': {
    pattern: /^I\ run\ the\ user\ summary\ report\ load\ job$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_summary.feature:9'],
  },
  'I should be redirected to the TTC portal home': {
    pattern: /^I\ should\ be\ redirected\ to\ the\ TTC\ portal\ home$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/login.feature:10'],
  },
  'I should be redirected to the TTC portal login page': {
    pattern: /^I\ should\ be\ redirected\ to\ the\ TTC\ portal\ login\ page$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/logout.feature:10'],
  },
  'I should receive a password reset prompt from the identity provider': {
    pattern: /^I\ should\ receive\ a\ password\ reset\ prompt\ from\ the\ identity\ provider$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/password_reset.feature:10'],
  },
  'I should receive a signed URL and upload key for the document': {
    pattern: /^I\ should\ receive\ a\ signed\ URL\ and\ upload\ key\ for\ the\ document$/,
    python: 'test/python/steps/uploads_steps.py:1',
    typescript: 'test/typescript/steps/uploads_steps.ts:1',
    features: ['specs/features/uploads/document_upload.feature:10'],
  },
  'I should receive a signed URL and upload key for the photo': {
    pattern: /^I\ should\ receive\ a\ signed\ URL\ and\ upload\ key\ for\ the\ photo$/,
    python: 'test/python/steps/uploads_steps.py:1',
    typescript: 'test/typescript/steps/uploads_steps.ts:1',
    features: ['specs/features/uploads/photo_upload.feature:10'],
  },
  'I should receive my saved configuration': {
    pattern: /^I\ should\ receive\ my\ saved\ configuration$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/config_management.feature:10'],
  },
  'I should receive that user\'s form data': {
    pattern: /^I\ should\ receive\ that\ user's\ form\ data$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/reporting_get_form_data.feature:10'],
  },
  'I should receive the available form instances': {
    pattern: /^I\ should\ receive\ the\ available\ form\ instances$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_instances.feature:10'],
  },
  'I should receive the combined user application data': {
    pattern: /^I\ should\ receive\ the\ combined\ user\ application\ data$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:16'],
  },
  'I should receive the participant list output': {
    pattern: /^I\ should\ receive\ the\ participant\ list\ output$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/participant_list.feature:10'],
  },
  'I should receive the stored form data': {
    pattern: /^I\ should\ receive\ the\ stored\ form\ data$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/get_form_data.feature:10'],
  },
  'I should receive the user application HTML': {
    pattern: /^I\ should\ receive\ the\ user\ application\ HTML$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:10'],
  },
  'I should receive the user application form data': {
    pattern: /^I\ should\ receive\ the\ user\ application\ form\ data$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_report.feature:22'],
  },
  'I should receive the user integrity data': {
    pattern: /^I\ should\ receive\ the\ user\ integrity\ data$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:16'],
  },
  'I should receive the user summary data': {
    pattern: /^I\ should\ receive\ the\ user\ summary\ data$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_summary.feature:16'],
  },
  'I should see a printable form view': {
    pattern: /^I\ should\ see\ a\ printable\ form\ view$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/print_form.feature:10'],
  },
  'I should see an unauthorized message': {
    pattern: /^I\ should\ see\ an\ unauthorized\ message$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/permissions.feature:10'],
  },
  'I should see my profile details and available reports': {
    pattern: /^I\ should\ see\ my\ profile\ details\ and\ available\ reports$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/home.feature:10'],
  },
  'I should see the DSN application questions': {
    pattern: /^I\ should\ see\ the\ DSN\ application\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/dsn_application.feature:10'],
  },
  'I should see the TTC applicant profile questions': {
    pattern: /^I\ should\ see\ the\ TTC\ applicant\ profile\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_applicant_profile.feature:10'],
  },
  'I should see the TTC application questions for that country': {
    pattern: /^I\ should\ see\ the\ TTC\ application\ questions\ for\ that\ country$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_application_non_us.feature:10'],
  },
  'I should see the TTC application questions for the United States': {
    pattern: /^I\ should\ see\ the\ TTC\ application\ questions\ for\ the\ United\ States$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_application_us.feature:10'],
  },
  'I should see the TTC evaluation questions': {
    pattern: /^I\ should\ see\ the\ TTC\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_evaluation.feature:10'],
  },
  'I should see the TTC evaluator profile questions': {
    pattern: /^I\ should\ see\ the\ TTC\ evaluator\ profile\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_evaluator_profile.feature:10'],
  },
  'I should see the TTC portal settings questions': {
    pattern: /^I\ should\ see\ the\ TTC\ portal\ settings\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/ttc_portal_settings.feature:10'],
  },
  'I should see the admin dashboard content': {
    pattern: /^I\ should\ see\ the\ admin\ dashboard\ content$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/access.feature:10'],
  },
  'I should see the admin settings content': {
    pattern: /^I\ should\ see\ the\ admin\ settings\ content$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/settings.feature:10'],
  },
  'I should see the disabled notice': {
    pattern: /^I\ should\ see\ the\ disabled\ notice$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/disabled.feature:10'],
  },
  'I should see the list of available report pages': {
    pattern: /^I\ should\ see\ the\ list\ of\ available\ report\ pages$/,
    python: 'test/python/steps/admin_steps.py:1',
    typescript: 'test/typescript/steps/admin_steps.ts:1',
    features: ['specs/features/admin/reports_pages.feature:10'],
  },
  'I should see the post-Sahaj TTC feedback questions': {
    pattern: /^I\ should\ see\ the\ post\-Sahaj\ TTC\ feedback\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_sahaj_ttc_feedback.feature:10'],
  },
  'I should see the post-Sahaj TTC self evaluation questions': {
    pattern: /^I\ should\ see\ the\ post\-Sahaj\ TTC\ self\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_sahaj_ttc_self_eval.feature:10'],
  },
  'I should see the post-TTC feedback questions': {
    pattern: /^I\ should\ see\ the\ post\-TTC\ feedback\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_ttc_feedback.feature:10'],
  },
  'I should see the post-TTC self evaluation questions': {
    pattern: /^I\ should\ see\ the\ post\-TTC\ self\ evaluation\ questions$/,
    python: 'test/python/steps/forms_steps.py:1',
    typescript: 'test/typescript/steps/forms_steps.ts:1',
    features: ['specs/features/forms/post_ttc_self_eval.feature:10'],
  },
  'I should see the rendered tab content with user context': {
    pattern: /^I\ should\ see\ the\ rendered\ tab\ content\ with\ user\ context$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/tabs.feature:10'],
  },
  'I sign in with a valid Google account': {
    pattern: /^I\ sign\ in\ with\ a\ valid\ Google\ account$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/login.feature:9'],
  },
  'I sign out of the TTC portal': {
    pattern: /^I\ sign\ out\ of\ the\ TTC\ portal$/,
    python: 'test/python/steps/auth_steps.py:1',
    typescript: 'test/typescript/steps/auth_steps.ts:1',
    features: ['specs/features/auth/logout.feature:9'],
  },
  'I submit form data to the upload form API': {
    pattern: /^I\ submit\ form\ data\ to\ the\ upload\ form\ API$/,
    python: 'test/python/steps/api_steps.py:1',
    typescript: 'test/typescript/steps/api_steps.ts:1',
    features: ['specs/features/api/upload_form.feature:9'],
  },
  'I update my user configuration': {
    pattern: /^I\ update\ my\ user\ configuration$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/config_management.feature:15'],
  },
  'I upload form data for a specific form instance': {
    pattern: /^I\ upload\ form\ data\ for\ a\ specific\ form\ instance$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/form_data_upload.feature:9'],
  },
  'I visit the disabled page': {
    pattern: /^I\ visit\ the\ disabled\ page$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/disabled.feature:9'],
  },
  'a certificate PDF should be generated': {
    pattern: /^a\ certificate\ PDF\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/certificate.feature:10'],
  },
  'a user integrity file should be generated': {
    pattern: /^a\ user\ integrity\ file\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:10'],
  },
  'a user summary file should be generated': {
    pattern: /^a\ user\ summary\ file\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_summary.feature:10'],
  },
  'an applicant enrolled list should be generated': {
    pattern: /^an\ applicant\ enrolled\ list\ should\ be\ generated$/,
    python: 'test/python/steps/reports_steps.py:1',
    typescript: 'test/typescript/steps/reports_steps.ts:1',
    features: ['specs/features/reports/user_integrity.feature:22'],
  },
  'my configuration should be saved': {
    pattern: /^my\ configuration\ should\ be\ saved$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/config_management.feature:16'],
  },
  'my form data should be stored for that instance': {
    pattern: /^my\ form\ data\ should\ be\ stored\ for\ that\ instance$/,
    python: 'test/python/steps/user_steps.py:1',
    typescript: 'test/typescript/steps/user_steps.ts:1',
    features: ['specs/features/user/form_data_upload.feature:10'],
  },
  'the API should accept the form submission': {
    pattern: /^the\ API\ should\ accept\ the\ form\ submission$/,
    python: 'test/python/steps/api_steps.py:1',
    typescript: 'test/typescript/steps/api_steps.ts:1',
    features: ['specs/features/api/upload_form.feature:10'],
  },
  'the TTC portal is in disabled mode': {
    pattern: /^the\ TTC\ portal\ is\ in\ disabled\ mode$/,
    python: 'test/python/steps/portal_steps.py:1',
    typescript: 'test/typescript/steps/portal_steps.ts:1',
    features: ['specs/features/portal/disabled.feature:8'],
  },
} as const;
