/**
 * Upload Token Verification API
 *
 * Verifies HMAC-signed upload tokens generated by the signed-url endpoint.
 * This endpoint can be used by post-upload handlers to validate tokens
 * before processing uploaded files.
 *
 * SECURITY: Uses environment-gated authentication based on AUTH_MODE:
 * - platform: Trust x-user-email header (App Engine with IAP)
 * - session: Validate bearer token with HMAC signature (standalone)
 */

import { verifyUploadToken, isUploadTokenExpired, getHmacSecret } from '../../../utils/crypto';
import { getAuthenticatedUser } from '../../../utils/auth';
import { readBodyWithLimit, isPayloadTooLargeError } from '../../../utils/request';
import { checkRateLimit } from '../../../utils/rate-limit';

interface VerifyRequest {
  key?: string;
}

// Security: Maximum JSON body size (4KB)
const MAX_BODY_SIZE = 4 * 1024;

const TOKEN_MAX_AGE_SECONDS = 15 * 60; // 15 minutes

export async function POST(request: Request): Promise<Response> {
  // 1. Security: Check authentication (uses AUTH_MODE to determine method)
  const user = await getAuthenticatedUser(request);
  if (!user) {
    return Response.json({ error: 'Authentication required' }, { status: 401 });
  }

  // 2. Security: Rate limiting to prevent abuse
  const rateLimit = await checkRateLimit(user);
  if (!rateLimit.allowed) {
    const retryAfterSeconds = Math.ceil((rateLimit.resetAt - Date.now()) / 1000);
    return Response.json(
      {
        error: 'RATE_LIMIT_EXCEEDED',
        message: 'Too many requests. Please try again later.',
        retryAfter: retryAfterSeconds,
      },
      {
        status: 429,
        headers: {
          'Retry-After': retryAfterSeconds.toString(),
          'X-RateLimit-Limit': rateLimit.limit.toString(),
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateLimit.resetAt.toString(),
        },
      }
    );
  }

  // 2. Parse request body with size limit
  let body: VerifyRequest;
  try {
    const bodyText = await readBodyWithLimit(request, MAX_BODY_SIZE);
    body = JSON.parse(bodyText) as VerifyRequest;
  } catch (e) {
    if (isPayloadTooLargeError(e)) {
      return Response.json({ error: 'Payload too large' }, { status: 413 });
    }
    return Response.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const { key } = body;

  // 3. Validate key presence
  if (!key || typeof key !== 'string') {
    return Response.json({ error: 'Upload key is required' }, { status: 400 });
  }

  // 4. Verify token signature
  const payload = verifyUploadToken(key, getHmacSecret());

  if (!payload) {
    return Response.json({ error: 'Invalid token' }, { status: 403 });
  }

  // 5. Check token expiration
  if (isUploadTokenExpired(payload, TOKEN_MAX_AGE_SECONDS)) {
    return Response.json({ error: 'Token expired' }, { status: 403 });
  }

  // 6. Verify ownership (token user must match authenticated user)
  if (payload.user !== user) {
    return Response.json({ error: 'Access denied' }, { status: 403 });
  }

  // 7. Return validated payload
  return Response.json({
    valid: true,
    payload: {
      user: payload.user,
      timestamp: payload.timestamp,
      filename: payload.filename,
    },
  });
}
